<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 25 Jul 2015 17:27:01 +0000 by Alec_Sadler
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'livesearchmemid' => "ID: ",
'lsnoresults' => "Нет результатов",
'ls_acppages' => "Разделы АЦ",
'ls_forums' => "Форумы",
'ls_groupresults' => "Групповые настройки, соответствующие поисковому запросу &raquo;",
'ls_groups' => "Группы",
'ls_grouptitles' => "Группы",
'ls_help' => "Разделы помощи",
'ls_members' => "Пользователи",
'ls_quick_search' => "Быстрый поиск",
'ls_settings' => "Настройки",
'ls_view_more_acp' => "Показать все разделы АЦ",
'ls_view_more_forums' => "Показать все форумы",
'ls_view_more_groups' => "Показать все группы",
'ls_view_more_help' => "Показать все разделы помощи",
'ls_view_more_mem' => "Показать всех пользователей",
'ls_view_more_settings' => "Показать все настройки",
 ); 
