<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 25 Jul 2015 17:27:01 +0000 by Alec_Sadler
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'fave_title' => "%s",
'freq_daily' => "Ежедневный отчет",
'freq_immediate' => "Незамедлительно",
'freq_offline' => "Когда я оффлайн",
'freq_weekly' => "Еженедельный отчет",
'label_anon' => "Подписаться анонимно",
'label_anon_desc' => "Не показывать меня в выборке",
'label_freq' => "Частота",
'label_notify' => "Получать уведомления",
'likeadded' => "Добавлено:",
'likedby' => "Подписаны",
'pg_no_longer_following' => "Вы больше не подписаны на это",
'pg_unfollow_confirm' => "Прекратить подписку",
'pg_unfollow_text' => "<strong>%s</strong>, вы хотите прекратить подписку на следующий контент: <a href='%s'>%s</a>.<br />При отмене подписки вы больше не будете получать уведомления об обновлениях.",
'pg_unfollow_title' => "Отменить подписку",
'pg_unlike_done' => "Вы отменили подписку",
 ); 
