<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 25 Jul 2015 17:27:01 +0000 by Alec_Sadler
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'choose_file' => "Выберите раздел",
'help_back_list_title' => "Назад к списку",
'help_read_document' => "Прочитать",
'help_return_list' => "Вернуться к списку разделов",
'help_topic' => "Раздел помощи",
'help_topics' => "Разделы помощи",
'help_txt' => "Выберите интересующий вас раздел помощи или воспользуйтесь поиском",
'no_help_topics' => "В данный момент в системе нет разделов помощи",
'page_title' => "Просмотр разделов помощи",
'topic_text' => "Выбранный вами раздел помощи",
 ); 
