<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 25 Jul 2015 17:27:01 +0000 by Alec_Sadler
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'h3_title_security' => "Доступные инструменты",
'sec_acp_htaccess_protection' => "Защита файлом '.htaccess' АЦ",
'sec_change_the_line_define_cp_dire' => "Измените строку: <pre>define( 'CP_DIRECTORY', '<strong>admin</strong>' );</pre> на <pre>define( 'CP_DIRECTORY', '<strong>admin_secret</strong>' );</pre>",
'sec_cp_htaccess_protection' => "Защита файлом '.htaccess' АЦ",
'sec_executable_files' => "Исполняемые файлы",
'sec_files_55k_or_larger' => "файлы размером свыше 55k",
'sec_file_size' => "(размер файла)",
'sec_filter' => "Фильтр",
'sec_first_youll_need_to_physically' => "Во-первых, вы должны переименовать директорию. Подключитесь к серверу при помощи FTP и найдите директорию с IPB (директория, в котором находится файл 'index.php').",
'sec_information' => "информация",
'sec_invision_power_board_can_write' => "Invision Power Board может создать файл '.htaccess', который защитит директорию админцентра. ",
'sec_ipboard_has_a_dedicated_direct' => "Invision Power Board обнаружил директорию админцентра. В целях повышения безопасности, вы можете изменить эту директорию.",
'sec_ipboard_is_unable_to_write_int' => "IP.Board не может создать файл в директории администратора",
'sec_ipboard_security_center' => "Центр безопасности IP.Board",
'sec_last_modified' => "Последнее изменение",
'sec_locate_the_admin_directory_cho' => "Найдите директорию 'admin'. Он содержит один файл - 'index.php'. Выберите команду «Переименовать» в вашей FTP-программе и укажите новое название. В этой инструкции мы будем использовать название 'admin_secret'. Если у вас в указанной директории создан файл защиты '.htaccess', вы ДОЛЖНЫ его удалить. В противном случае вы не сможете авторизоваться в админцентр. Вы сможете создать этот файл заново после выполнения следующего шага.  ",
'sec_locate_the_initdataphp_file_th' => "Найдите файл 'initdata.php'. Он находится в корневой директории IPB. Скачайте его и откройте в текстовом редакторе.",
'sec_modified_in_the_past_30_days' => "измененные за последние 30 дней",
'sec_password' => "Пароль",
'sec_please_create_a_file_called_ht' => "Пожалуйста создайте файл с названием \".htpasswd\". Добавьте нижеследующие строки в него и загрузите его в директорию 'admin' на сервере.",
'sec_please_create_a_file_called_ht_1' => "Пожалуйста создайте файл с названием \".htaccess\". Добавьте нижеследующие строки в него и загрузите его в директорию 'admin' на сервере.",
'sec_please_note' => "Помните",
'sec_proceed' => "Создать файл",
'sec_renaming_the_cp_sitecontrol_di' => "Изменение директории АЦ",
'sec_score_5_or_more' => "с рейтингом 5 или выше",
'sec_score_6_or_more' => "с рейтингом 6 или выше",
'sec_score_7_or_more' => "с рейтингом 7 или выше",
'sec_score_8_or_more' => "с рейтингом 8 или выше",
'sec_score_9_or_more' => "с рейтингом 9 или выше",
'sec_show' => "Показать",
'sec_show_all' => "все",
'sec_step_1' => "Шаг 1:",
'sec_step_2' => "Шаг 2:",
'sec_the_security_center_is_a_centr' => "Центр безопасности — это хранилище инструментов и настроек, отвечающих за безопасность форума.",
'sec_username' => "Имя пользователя",
'sec_using_this_tool_will_overwrite' => "Используя этот инструмент, вы перезапишите любой имеющийся файл защиты в директории админцентра. После сохранения данных, вам будет предложено ввести указанные имя пользователя и пароль. Хотим заметить, что если вы переименуете директорию админцентра, вам так же будет необходимо удалить этот файл при помощи FTP-клиента — в противном случае доступ в админцентр для вас будет заблокирован.",
'sec_your_cp_directory_has_now_been' => "Теперь директория вашего админцентра изменена.",
'sec_your_installation_is_checked_a' => "При помощи настроек и инструментов ниже вы сможете проверить и повысить безопасность вашего IPB.",
'skin_edit_member' => "Изменить",
'skin_header_admins' => "Пользователи, имеющие доступ в АЦ",
'skin_header_virus' => "Проверенные директории",
'skin_suspicious_files' => "Подозрительные файлы",
'skin_th_email' => "E-mail адрес",
'skin_th_filesize' => "(Размер) &nbsp; Последнее изменение",
'skin_th_ip' => "IP адрес",
'skin_th_name' => "Пользователь",
'skin_th_posts' => "Сообщений",
'skin_th_primary_group' => "Основная группа",
'skin_th_secondary_group' => "Второстепенная группа",
 ); 
