<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 25 Jul 2015 17:27:01 +0000 by Alec_Sadler
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'mi_cant_import' => "Невозможно импортировать",
'mi_current_title' => "Текущие изображения мобильного приложения",
'mi_error_cannot_write' => "Директория %s не имеет прав на запись",
'mi_error_doesnt_exist' => "Директория %s не существует",
'mi_error_images_writeable' => "Некоторые изображения не могут быть записаны, детали ниже",
'mi_error_missing_img' => "Изображение %s некорректное!",
'mi_error_no_export' => "Экспорт не прошел!",
'mi_error_refresh_failed' => "Обновление не прошло!",
'mi_exportxml' => "Экспортировать как XML-архив",
'mi_img_not_dims' => "Некорретный размер, должно быть %s",
'mi_img_not_writable' => "Нет прав на запись",
'mi_import_failed' => "Импортирование не прошло!",
'mi_import_title' => "Импорт изображений XML-архивом",
'mi_information' => "Если вы хотите заменить эти изображения, вы можете использовать кнопку \"<strong>Импорт изображений XML-архивом</strong>\", или вы можете индивидуально загружать изображения в директорию <strong>%s</strong> на вашем сервере. Если вы загружаете вручную файлы, не забывайте обновлять кеши после этого.",
'mi_recache' => "Обновить кеши",
'mi_recache_done' => "Перестроение кеша завершено",
'mi_select_xml' => "Выбрать XML-архив",
'mi_title' => "Изображения iOS App",
'mi_tt_filename' => "Имя",
'mi_tt_modified' => "Изменено",
'mi_tt_size' => "Размер",
'mi_upload' => "Загрузить",
 ); 
