<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 25 Jul 2015 17:27:01 +0000 by Alec_Sadler
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'applications_title' => "Приложение",
'author_suffix' => "Автор:",
'bbcode_and_media' => "Добавлены теги bb-кода и медиа-теги",
'continue_button' => "Продолжить",
'current_version' => "Текущая версия:",
'cur_version_none' => "Нет",
'duplicate_tables' => "Существующие таблицы:",
'dup__drop' => "Удалить оригинальные и создать новые",
'dup__skip' => "Пропустить",
'error__cannot_init' => "Не удалось инициировать установочный класс",
'error__continue' => "Нажмите здесь, если все равно хотите продолжить",
'error__display' => "Возникли следующие ошибки:",
'error__file_chmod' => "Нельзя записать в файл %s",
'error__file_missing' => "Файл %s не существует",
'error__file_needed' => "Файл %s не существует",
'error__up_to_date' => "Приложение последней версии",
'hooks_nofile' => "Нет хуков для установки",
'imported_no_help' => "Нет разделов помощи для добавления",
'imported_x_help' => "Добавлено %s разделов помощи",
'install_latest' => "установка последней версии",
'install_skins_flag_recache' => "Все стили помечены для пересоздания кешей",
'ipboard_setup_title' => "Инструмент установки",
'ipboard_welcome_setup' => "Вас приветствует установщик IP.Board.",
'no_bbcode_media' => "Нет bb-кодов и медиа-тегов для добавления",
'no_tasks_for_import' => "Нет задач для добавления",
'please_correct_errors' => "Прежде чем продолжить необходимо исправить следующие ошибки:",
'progress_report' => "Прогресс:",
'redir__appmodule_run' => "Запуск модуля",
'redir__continue' => "Для продолжения нажмите сюда, если вас не переместило автоматически",
'redir__cssfiles' => "%s css добавлено, %s обновлено в стиле %s",
'redir__hooks' => "%s хуков добавлено, %s обновлено",
'redir__nolanguages' => "Нет языковых фраз для добавления",
'redir__nomore_modules' => "Больше нет модулей для запуска",
'redir__nomore_sql' => "SQL запросов больше нет",
'redir__no_templates' => "Нет шаблонов для добавления",
'redir__no_template_re' => "Нет шаблонов для добавления. Пропускаем обновление стилей.",
'redir__replacements' => "Макросов добавлено",
'redir__sql_indexes' => "%s индексов добавлено",
'redir__sql_inserts' => "%s данных добавлено",
'redir__sql_run' => "%s SQL запросов выполнено",
'redir__sql_tables' => "%s таблиц добавлено, %s пропущено",
'redir__templates' => "%s шаблонов добавлено, %s обновлено в стиле %s",
'redir__upgraded_to' => "Обновлено до версии %s, запуск следующего модуля",
'return_to_overview' => "Нажмите здесь для возвращения к списку приложений",
'type__install' => "Установка",
'type__installation' => "установка",
'type__text' => "%s выполняется",
'type__text_finished' => "Завершен этап: %s",
'type__upgrade' => "Обновление",
'type__upgradet' => "обновление",
'upgrade_latest' => "обновление до последней версии",
'version_suffix' => "Версия:",
 ); 
