<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 25 Jul 2015 17:27:01 +0000 by Alec_Sadler
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'pal_attachment_space_used' => "Место под прикрепленные файлы использовано",
'pal_attach_attach_insert' => "Добавить прикрепленный файл в сообщение",
'pal_attach_attach_removal' => "Удаление прикрепленного файла...",
'pal_attach_attach_remove' => "Удалить прикрепленный файл",
'pal_attach_attach_removed' => "Прикрепленный файл удален",
'pal_attach_init_progress' => "Инициализация прикрепленных файлов",
'pal_attach_invalid_mime_type' => "Загрузка не удалась. Вам не разрешено загружать этот тип файлов",
'pal_attach_no_items' => "В настоящее время элементов нет",
'pal_attach_no_upload' => "Загрузка не удалась. Не выбран файл для загрузки",
'pal_attach_no_upload_dir' => "Загрузка не удалась. Сообщите администратору о неверных правах доступа к директории загружаемых файлов",
'pal_attach_no_upload_dir_perms' => "Загрузка не удалась. Пожалуйста, сообщите администратору о неверных правах доступа к директории загружаемых файлов",
'pal_attach_ready' => "Система загрузки файлов готова",
'pal_attach_remove_warn' => "Удалить прикрепленный файл ?",
'pal_attach_uploading_file' => "Загрузка файла",
'pal_attach_upload_failed' => "Загрузка неудачна. Попросите администратора проверить настройки и права доступа",
'pal_attach_upload_ok' => "Загрузка завершена успешно. Загруженные файлы доступны в «Управление текущими файлами»",
'pal_attach_upload_too_big' => "Загрузка не удалась. Размер файла больше чем доступное пространство на диске",
'pal_back' => "Назад",
'pal_bgroups' => "Группы",
'pal_blocks' => "Блоки",
'pal_close_library' => "Закрыть библиотеку",
'pal_delete_item' => "Удалить элемент",
'pal_extract_media' => "Извлечь",
'pal_file_space_used' => "Файловое пространство использовано",
'pal_green_added_text' => "Зеленый: добавленный текст",
'pal_images' => "Изображения",
'pal_insert' => "Вставить...",
'pal_insert_item' => "Вставить элемент",
'pal_item' => "Элемент",
'pal_legend' => "Подпись",
'pal_max_single_upload_size' => "Максимальный размер загружаемого файла:",
'pal_max_single_upload_size_1' => "Максимальный размер загружаемого файла:",
'pal_no_open_editors_to_extract_med' => "Ни один редактор не открыт для загрузки видео из",
'pal_of' => "из",
'pal_options' => "Настройки",
'pal_pages' => "Страницы",
'pal_preview' => "Предпросмотр",
'pal_red_removed_text' => "Красный: удаленный текст",
'pal_select_a_file' => "Выберите файл",
'pal_show_item' => "Показать элемент",
'pal_template' => "шаблон",
'pal_templates' => "Шаблоны",
'pal_upload' => "ЗАГРУЗИТЬ",
'pal_url' => "URL",
'pal_urls' => "URLs",
'pal_view_raw_html' => "Необработанный HTML",
'pal_view_wrapped_html' => "Обработанный HTML",
 ); 
