<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 25 Jul 2015 17:27:01 +0000 by Alec_Sadler
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'approve_link' => "Опубликовать",
'approve_x_comments' => "Опубликовать",
'check_all' => "Выбрать все",
'click here to login' => "нажмите чтобы войти",
'comments_act_go' => "ОК",
'comments_header' => "Комментарии",
'comment_action_count' => "С <span id='comment_count'>#{count}</span> отмеченными комментариями:",
'comment_approval_required' => "Ваш комментарий должен быть проверен модератором.",
'comment_button_post' => "Добавить",
'comment_hidden_content' => "Свернуть",
'comment_notice_subject' => "Добавлен комментарий <a href='%s'>%s</a>",
'comment_notifications' => "<#NAME#>,

<#AUTHOR#> прокоментировал \"<#TITLE#>\".

<#COMMENT#>

Коментарий расположен по следующему адресу:
<#URL#>",
'comment_permalink' => "Получить прямую ссылку",
'comment_reply' => "Ответить",
'comment_save' => "Сохранить",
'comm_confirm_delete' => "Подтверждение",
'comm_confirm_delete_desc' => "Вы действительно хотите удалить этот комментарий?",
'comm_confirm_hide' => "Скрыть",
'comm_confirm_hide_desc' => "Комментарий будет скрыт для пользователей, но модераторы смогут его видеть",
'delete_comment' => "Удалить",
'delete_link' => "Удалить",
'delete_x_comments' => "Удалить",
'del_comm_now' => "Удалить комментарий",
'edit_comment' => "Редактирование комментария от:",
'edit_link' => "Изменить",
'hide_link' => "Скрыть",
'hide_x_comments' => "Скрыть",
'ignored_comments_not' => "Комментарий скрыт, так как вы игнорируете сообщения от ",
'manage_comments_pop' => "Управление комментариями",
'mobile_add_comment' => "Добавить комментарий",
'mq_image_add' => "Цитата",
'no_reason_given' => "Без причины",
'permalink' => "Ссылка:",
'post_deleted_by' => "Комментарий скрыт ",
'reply_to_comment' => "Ответить на комментарий",
'report_link' => "Жалоба",
'sign_in' => "Войти",
'unapprove_x_comments' => "Скрыть",
'unhide_link' => "Показать",
'unhide_x_comments' => "Показать",
'view_comment' => "Посмотреть",
'view_it_anyway' => "Посмотреть?",
'yourname_captcha' => "Ваше имя:",
 ); 
