<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 25 Jul 2015 17:27:01 +0000 by Alec_Sadler
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'bad_email_password' => "Неверные данные для входа",
'enter_name_and_email' => "Логин или Email",
'enter_useremail' => "Email",
'enter_username' => "Логин",
'ipb_login' => "Invision Power Board: Вход",
'logout_complete' => "Вы вышли",
'no_acp_access' => "У вас не достаточно прав для доступа в админцентр",
 ); 
