<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 25 Jul 2015 17:27:01 +0000 by Alec_Sadler
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'ep_access_denied' => "You do not have permission to view this page.",
'ep_not_found' => "Sorry, we could not locate the page you are requesting to view.",
 ); 
