<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 25 Jul 2015 17:27:01 +0000 by Alec_Sadler
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'spam_graph_title' => "Последние регистрации",
'spam_ok' => "ОК",
'spam_spam' => "Спам",
'statisnotspam' => "Не спам",
'statisspam' => "Спам",
'stats_apr' => "Апрель",
'stats_asc' => "По возрастанию — первые: самые старые",
'stats_aug' => "Август",
'stats_count' => "Кол-во",
'stats_daily' => "Ежедневно",
'stats_date' => "Дата",
'stats_datefrom' => "<strong>Дата с</strong>",
'stats_dateto' => "<strong>Дата по</strong>",
'stats_dec' => "Декабрь",
'stats_desc' => "По убыванию — первые: самые новые",
'stats_feb' => "Февраль",
'stats_fromincorrect' => "«Дата с:» — неверное время. Пожалуйста, проверьте введенное вами значение.",
'stats_jan' => "Январь",
'stats_jul' => "Июль",
'stats_jun' => "Июнь",
'stats_mar' => "Март",
'stats_may' => "Май",
'stats_monthly' => "Ежемесячно",
'stats_msg' => "Статистика личных сообщений",
'stats_msg_nav' => "Отправленные личные сообщения",
'stats_nov' => "Ноябрь",
'stats_oct' => "Октябрь",
'stats_post' => "Статистика сообщений",
'stats_post_nav' => "Количество сообщений",
'stats_reg' => "Статистика регистраций",
'stats_reg_nav' => "Зарегистрировавшиеся пользователи",
'stats_results' => "Результат",
'stats_sep' => "Сентябрь",
'stats_show' => "Показать",
'stats_sorting' => "<strong>Сортировка результатов</strong>",
'stats_spam' => "Статистика спам сервиса",
'stats_timescale' => "<strong>Период времени</strong>",
'stats_title' => "Статистика",
'stats_title_results' => "Результаты статистики",
'stats_to' => " по ",
'stats_toincorrect' => "«Дата до:» — неверное время. Пожалуйста, проверьте введенное вами значение",
'stats_topic' => "Статистика новых тем",
'stats_topic_nav' => "Новых тем",
'stats_total' => "<strong>Всего</strong>",
'stats_views' => "Статистика просмотров тем",
'stats_views_nav' => "Просмотры тем",
'stats_weekly' => "Еженедельно",
'stats_weekno' => "Неделя #",
'timescale_daily' => "За день",
'timescale_monthly' => "За месяц",
'timescale_weekly' => "За неделю",
'topic_view_warning' => "Статистика отображает число просмотров тем, созданных в указанный период. Она не отображает число просмотров в указанный период.",
 ); 
