<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 25 Jul 2015 17:27:01 +0000 by Alec_Sadler
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'forum_leaders' => "Администрация",
'goto_profile' => "Перейти к профилю",
'go_button' => "OK",
'leader_all_forums' => "Все форумы",
'leader_forums' => "Форумы",
'leader_group' => "Группа",
'leader_last_seen' => "Последнее действие",
'leader_name' => "Имя пользователя",
'member' => "Имя пользователя",
'member_joined' => "Регистрация",
'member_percent' => "% сегодняшних сообщений",
'member_posts' => "Всего сообщений",
'member_today' => "Сообщений сегодня",
'm_online' => "В сети",
'notopic_attach' => "Не удалось загрузить прикрепленные файлы для запрашиваемой темы",
'no_forums' => "Посмотреть %s форумов",
'no_info' => "На данный момент нет никакой информации",
'stats_missing_tid' => "Вы должны указать существующую тему, чтобы воспользоваться этой функцией.",
'todays_posters' => "20 авторов сегодня",
'top20rep_reputation' => "Баллов репутации",
'top20rep_title' => "Пользователи с наибольшим количеством баллов репутации",
'topic_noattach' => "Тема не содержит прикрепленных файлов",
'topic_noperms' => "Вы не можете просматривать этот форум",
'top_poster_title' => "20 авторов сегодня",
'whoposted_name' => "Имя пользователя",
'whoposted_posts' => "Сообщений",
'who_farted' => "Отвечали в:",
'who_replied_title' => "Кто отвечал в эту тему",
 ); 
