<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 25 Jul 2015 17:27:01 +0000 by Alec_Sadler
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'mem_change_button' => "Изменить",
'mem_posts' => "Сообщения",
'm_overrride' => "Переопределить права группы следующими масками",
 ); 
