<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 25 Jul 2015 17:27:01 +0000 by Alec_Sadler
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'disable' => "Удалить",
'enable' => "Добавить",
'enabled' => "Статус",
'group_name_indicator' => "Легенда групп пользователей",
'g_hidden' => " скрыта",
'g_shown' => " добавлена",
'g_successfully' => "Группа успешно",
'g_title' => "Группы",
'hidden_groups' => "Скрытые группы",
'm_display_order' => "Управление отображением групп",
'no_toggle_guest' => "Не удается переключить группу гостей",
'postform_badmd5' => "Bad key supplied",
'shown_groups' => "Просмотр групп",
 ); 
