<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 25 Jul 2015 17:27:01 +0000 by Alec_Sadler
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'ascending_order' => "порядке возрастания",
'descending_order' => "порядке убывания",
'edit_member' => "Редактировать",
'members_start_with' => "Просмотреть пользователей с именами начинающимися с ",
'member_group' => "Группа",
'member_has_x_rep' => "%s имеет %s баллов репутации",
'member_has_x_rep_like' => "%s имеет %s лайков",
'member_joined' => "Дата",
'member_name' => "Имя",
'member_posts' => "сообщений",
'mlist_adv_filt' => "Дополнительные фильтры",
'mlist_adv_filt_opt' => "Фильтры поиска",
'mlist_header' => "Список пользователей",
'mlist_view_all_title' => "Просмотреть всех пользователей",
'mlist_view_all_txt' => "ВСЕ",
'mlist_view_start_title' => "Просмотреть пользователей с именами начинающимися с",
'm_dd_views' => "по количеству просмотров профиля",
'm_rating' => "Рейтинг",
'm_rating_morethan' => "Рейтинг выше чем",
'm_stars' => "баллов",
'm_views' => "Просмотров",
'no_results' => "Нет совпадений",
'page_title' => "Список пользователей",
'pcount' => "По количеству сообщений",
'photo_only' => "Загрузил фотографию",
'reputation' => "Репутация",
'show_all' => "Показать всех",
'sorting_text_by' => ", сортировать",
'sorting_text_in' => "в",
'sorting_text_results' => "результатов на страницу",
'sorting_text_with' => "по",
'sorty_by_jdate' => "Сортировать по дате регистрации",
'sort_by' => "Сортировать: ",
'sort_by_joined' => "по дате регистрации",
'sort_by_mname' => "Сортировать по имени пользователя",
'sort_by_name' => "по имени пользователя",
'sort_by_posts' => "по количеству сообщений",
'sort_submit' => "Применить фильтры",
's_after' => "после",
's_before' => "до",
's_begins' => "начинается с",
's_contains' => "содержит",
's_dateformat' => "(ДД-ММ-ГГГГ)",
's_joined' => "Дата регистрации",
's_lastpost' => "Последнее сообщение",
's_lastvisit' => "Время последнего посещения",
's_lessthan' => "меньше чем",
's_morethan' => "больше чем",
's_name' => "По имени пользователя",
's_posts' => "Количество сообщений",
's_signature' => "Подпись содержит",
 ); 
