<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 25 Jul 2015 17:27:01 +0000 by Alec_Sadler
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'board_index' => "Просматривает главную страницу форума",
'member_name' => "Имя",
'not_online' => "Не в сети",
'no_options_available' => "Нет действий",
'online_page_title' => "Пользователи в онлайн",
's_by' => "Сортировать по: ",
's_go' => "Обновить",
's_show_mem_all' => "Показать всех",
's_show_mem_guest' => "Показать только гостей",
's_show_mem_reg' => "Показать только зарегистрированных",
's_sort_key_click' => "Последним действиям",
's_sort_key_name' => "Именам",
's_sort_order_asc' => "В порядке возрастания",
's_sort_order_desc' => "В порядке убывания",
'time' => "Время",
'users_online' => "Кто в онлайне",
'where' => "Последнее действие",
'WHERE_boardrules' => "Читает правила",
'WHERE_calendar' => "Просматривает календарь",
'WHERE_forward' => "Отправляет ссылку на тему по e-mail",
'WHERE_help' => "Просматривает разделы помощи",
'WHERE_invite' => "Приглашает друга на форум",
'WHERE_login' => "Авторизуется",
'WHERE_mail' => "Пишет пользователю e-mail",
'WHERE_members' => "Просматривает список пользователей",
'WHERE_msg' => "Использует почтовый ящик",
'WHERE_online' => "Просматривает список <b>Кто в онлайне</b>",
'WHERE_portal' => "Смотрит портал",
'WHERE_postnew' => "Отвечает в форуме:",
'WHERE_postrep' => "Отвечает в тему:",
'WHERE_print' => "Просматривает версию для печати",
'WHERE_profile' => "Просматривает профиль:",
'WHERE_reg' => "Регистрируется",
'WHERE_reports' => "Просматривает жалобы",
'WHERE_search' => "Ищет",
'WHERE_sf' => "Просматривает форум:",
'WHERE_sr' => "Читает правила форума:",
'WHERE_st' => "Читает тему:",
'WHERE_stats' => "Просматривает Статистику",
'WHERE_usercp' => "Просматривает или изменяет профиль",
 ); 
