<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 9               */
/* CACHE FILE: Generated: Sat, 01 Aug 2015 13:33:44 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_profile_9 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['acknowledgeWarning'] = array('valueIsPermanent','hasValue','options','memberNote','hasReasonAndContent','hasContent','hasReason','hasExpireDate','hasExpiration','hasPoints','isVerbalWarning');
$this->_funcHooks['addWarning'] = array('reasons','canUseAsBanGroup','banGroups','hasOtherOption','currentMq','currentRpa','currentSuspend');
$this->_funcHooks['customField__gender'] = array('male','female','nottelling','gender_set');
$this->_funcHooks['customField__generic'] = array('genericIsArray');
$this->_funcHooks['customFieldGroup__contact'] = array('cfieldgroups','cf_icon','cf_skype','cf_jabber','cf_website','cf_icq','cf_yahoo','cf_msn','cf_aim','cf_array','contact_field');
$this->_funcHooks['customizeProfile'] = array('hasBackgroundColor','backgroundIsFixed','hasBackgroundImage','hasBodyCustomization');
$this->_funcHooks['dnameWrapper'] = array('records','isAjaxModule','hasDnameHistory');
$this->_funcHooks['explainPoints'] = array('reasons','valueIsPermanent','hasValue','options','actions','hasActions');
$this->_funcHooks['friendsList'] = array('norep','posrep','negrep','repson','weAreSupmod','addfriend','notus','sendpm','blog','gallery','norep','posrep','negrep','repson','loopOnPending','friendsList','friendListPages','tabIsList','tabIsPending','friendListNone','hasFriendsList','friendListPagesBottom');
$this->_funcHooks['listWarnings'] = array('hasReason','warnings','paginationTop','canWarn','hasPaginationOrWarn','noWarnings','paginationBottom');
$this->_funcHooks['photoEditor'] = array('canHasUpload','canHasURL','allowGravatars','hasTwitter','hasFacebook');
$this->_funcHooks['reputationPage'] = array('isTheActiveApp','apps','hasMoreThanOneApp','hasResults');
$this->_funcHooks['showCard'] = array('cardRepPos','cardRepNeg','cardRepZero','cardRep','cardSendPm','cardStatus','cardOnline','cardWhere','isadmin','authorspammerinner','authorspammer','cardIsFriend','cardFriend','cardBlog','cardGallery');
$this->_funcHooks['statusReplies'] = array('canDelete','innerLoop','noWrapperTop','noWrapperBottom');
$this->_funcHooks['statusUpdates'] = array('isUs','moderated','forSomeoneElse','noLocked','cImg','creatorText','canDelete','isLocked','canLock','isUnapproved','addReturn','hasMore','hasReplies','canReply','maxReplies','statusApproved','outerLoop');
$this->_funcHooks['statusUpdatesPage'] = array('tabactive','tabactive2','updateTwitter','updateFacebook','update','canCreate','hasUpdates','hasPagination');
$this->_funcHooks['tabFriends'] = array('friends','friends_loop','friends');
$this->_funcHooks['tabReputation'] = array('isTheActiveApp','apps','hasMoreThanOneApp','currentIsGiven','canViewRep','currentIsReceived','hasResults','bottomPagination');
$this->_funcHooks['tabReputation_calendar'] = array('postMid','postMember','postMid','postMember');
$this->_funcHooks['tabReputation_posts'] = array('notLastFtAsForum','topicsForumTrail','postMid','postMember','hasForumTrail');
$this->_funcHooks['tabSingleColumn'] = array('singleColumnUrl','singleColumnTitle','date');
$this->_funcHooks['tabStatusUpdates'] = array('updateTwitter','updateFacebook','update','canCreate','leave_comment','hasUpdates');


}

/* -- acknowledgeWarning --*/
function acknowledgeWarning($warning) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['acknowledgeWarning'] ) )
{
$count_9376fd7712c85e9b29d0f884593e5253 = is_array($this->functionData['acknowledgeWarning']) ? count($this->functionData['acknowledgeWarning']) : 0;
$this->functionData['acknowledgeWarning'][$count_9376fd7712c85e9b29d0f884593e5253]['warning'] = $warning;
}
$IPBHTML .= "<h1 class='ipsType_pagetitle'>{$this->lang->words['warnings_acknowledge']}</h1>
<br />
<p class='message'>{$this->lang->words['warnings_acknowledge_desc']}</p>
<br />
<form action=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&module=profile&section=warnings&do=do_acknowledge", "public",'' ), "", "" ) . "\" method=\"post\">
	<input type='hidden' name='member' value='{$warning['wl_member']}' />
	<input type='hidden' name='id' value='{$warning['wl_id']}' />
	<input type='hidden' name='secure_key' value='{$this->member->form_hash}' />
	<input type='hidden' name='ref' value='{$_SERVER['HTTP_REFERER']}' />
	<div class='ipsBox'>
		" . (($warning['wl_note_member']) ? ("
			<div class='ipsBox_container ipsPad'>
				{$warning['wl_note_member']}
			</div>
			<br />
		") : ("")) . "
		<div class='ipsBox_container ipsPad'>
			" . (($warning['wl_reason']) ? ("" . (($warning['content']) ? ("
					" . sprintf( $this->lang->words['warning_blurb_yy'], "" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($warning['wl_moderator']) : '' ) . "", $warning['wl_reason']['wr_name'], $warning['content'] ) . "
				") : ("
					" . sprintf( $this->lang->words['warning_blurb_yn'], "" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($warning['wl_moderator']) : '' ) . "", $warning['wl_reason']['wr_name'] ) . "
				")) . "") : ("" . (($warning['content']) ? ("
					" . sprintf( $this->lang->words['warning_blurb_ny'], "" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($warning['wl_moderator']) : '' ) . "", $warning['content'] ) . "
				") : ("
					" . sprintf( $this->lang->words['warning_blurb_nn'], "" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($warning['wl_moderator']) : '' ) . "" ) . "
				")) . "")) . "
			<br />
			" . ((!$warning['wl_points'] and !$warning['wl_mq'] and !$warning['wl_rpa'] and !$warning['suspend']) ? ("
				{$this->lang->words['warnings_verbal_only']}
			") : ("" . (($warning['wl_points']) ? ("" . (($warning['wl_expire']) ? ("" . (($warning['wl_expire_date']) ? ("
							" . sprintf( $this->lang->words['warnings_given_points_expire'], $warning['wl_points'], $this->lang->getDate( $warning['wl_expire_date'], 'SHORT' ) ) . "<br />
						") : ("
							" . sprintf( $this->lang->words['warnings_given_points_expired'], $warning['wl_points'] ) . "<br />
					")) . "") : ("
						" . sprintf( $this->lang->words['warnings_given_points'], $warning['wl_points'] ) . "<br />
					")) . "") : ("")) . "
				".$this->__f__527c2d71fdf55dd193377368bf33b42e($warning)."")) . "
		</div>
	</div>
	<fieldset class='submit'>
		<input type='submit' class='input_submit' value='{$this->lang->words['warnings_acknowledge_confirm']}' />
	</fieldset>
</form>";
return $IPBHTML;
}


function __f__527c2d71fdf55dd193377368bf33b42e($warning)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( array( 'mq', 'rpa', 'suspend' ) as $k )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					" . (($warning[ 'wl_' . $k ]) ? ("" . (($warning[ 'wl_' . $k ] == -1) ? ("
							" . sprintf( $this->lang->words[ 'warnings_' . $k ], $this->lang->words['warnings_permanently'] ) . "<br />
						") : ("
							" . sprintf( $this->lang->words[ 'warnings_' . $k ], sprintf( $this->lang->words['warnings_for'], $warning[ 'wl_' . $k ], $this->lang->words[ 'warnings_time_' . $warning[ 'wl_' . $k . '_unit' ] ] ) ) . "<br />
						")) . "") : ("")) . "
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- addWarning --*/
function addWarning($member, $reasons, $errors, $editor, $currentPunishments) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['addWarning'] ) )
{
$count_c85068249d487973088af5047f6826d0 = is_array($this->functionData['addWarning']) ? count($this->functionData['addWarning']) : 0;
$this->functionData['addWarning'][$count_c85068249d487973088af5047f6826d0]['member'] = $member;
$this->functionData['addWarning'][$count_c85068249d487973088af5047f6826d0]['reasons'] = $reasons;
$this->functionData['addWarning'][$count_c85068249d487973088af5047f6826d0]['errors'] = $errors;
$this->functionData['addWarning'][$count_c85068249d487973088af5047f6826d0]['editor'] = $editor;
$this->functionData['addWarning'][$count_c85068249d487973088af5047f6826d0]['currentPunishments'] = $currentPunishments;
}
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("warn", "0" ) . "
<h1 class='ipsType_pagetitle'>" . sprintf( $this->lang->words['warnings_add_for'], $member['members_display_name'] ) . "</h1>
<br />
<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=warnings&amp;do=save&amp;member={$member['member_id']}", "public",'' ), "", "" ) . "' method='post'>
	<input type='hidden' name='from_app' value='{$this->request['from_app']}' />
	<input type='hidden' name='from_id1' value='{$this->request['from_id1']}' />
	<input type='hidden' name='from_id2' value='{$this->request['from_id2']}' />
	<div class='ipsBox'>
		<div class='ipsBox_container ipsPad'>
			<ul class='ipsForm ipsForm_vertical'>
				<li class='ipsField ipsField_select'>
					<label class='ipsField_title'>{$this->lang->words['warnings_reason']} <span class='ipsForm_required'>*</span></label>
					<div class='ipsField_content'>
						<select name='reason' id='reason-select'>
							<option value=''>{$this->lang->words['warnings_reason_select']}</option>
							".$this->__f__70808ea6434f889fd1dc5ca2e2e66483($member,$reasons,$errors,$editor,$currentPunishments)."							" . (($this->settings['warnings_enable_other'] or $this->memberData['g_access_cp']) ? ("
								<option value='0'>{$this->lang->words['warnings_reasons_other']}</option>
							") : ("")) . "
						</select>
						<span class='error'>{$errors['reason']}</span>
					</div>
				</li>
				<li class='ipsField ipsField_select' style='display:none' id='points-li'>
					<label class='ipsField_title'>{$this->lang->words['warnings_points']} <span class='ipsForm_required'>*</span></label>
					<div class='ipsField_content'>
						<input name='points' class='input_text' size='5' id='points-field' />
						<a href='#' id='points-explain-button'><img src=\"{$this->settings['img_url']}/help.png\" alt='{$this->lang->words['warnings_points_explain']}' title='{$this->lang->words['warnings_points_explain']}' /></a>
						<span class='error'>{$errors['points']}</span>
					</div>
				</li>
				<li class='ipsField'>
					<label class='ipsField_title'>{$this->lang->words['warnings_note_member']}</label>
					<div class='ipsField_content'>
						{$editor['member']}
						<span class='error'>{$errors['note_member']}</span>
					</div>
					<span class='desc'>{$this->lang->words['warnings_note_member_desc']}</span>
					<br />
					<span class='error'>{$errors['note_member']}</span>
				</li>
				<li class='ipsField'>
					<label class='ipsField_title'>{$this->lang->words['warnings_note_mods']}</label>
					<div class='ipsField_content'>
						{$editor['mod']}
						<span class='error'>{$errors['note_member']}</span>
					</div>
					<span class='desc'>{$this->lang->words['warnings_note_mods_desc']}</span>
					<br />
					<span class='error'>{$errors['note_member']}</span>
				</li>
				<li class='ipsField' id='punishment_li'>
					<label class='ipsField_title'>{$this->lang->words['warnings_punishment']}</label>
					<div class='ipsField_content'>
						<p class='message unspecific'>
							<span id='specified-punishment'>{$this->lang->words['warnings_punishment_select']}</span>
							<br />
							<a href='#' class='ipsButton_secondary' id='change-punishment-button' style='display:none'>{$this->lang->words['warnings_verbal_change']}</a>
						</p>
					</div>
				</li>
				<li class='ipsField' style='display:none' id='mq_li'>
					<label class='ipsField_title'>{$this->lang->words['warnings_punishment_mq']}</label>
					<div class='ipsField_content'>
						" . (($currentPunishments['mq']) ? ("
							<span class='error'>{$currentPunishments['mq']}{$this->lang->words['warnings_already_change']}<br /></span>
						") : ("")) . "
						<input type='checkbox' name='mq_perm' id='mq_perm' /> <label for='mq_perm'>{$this->lang->words['warnings__permanently']}</label>
						<span id='mq_time'>{$this->lang->words['warnings_or_for']} <input name='mq' class='input_text' size='2' id='mq_input' /> <select name='mq_unit' id='mq_unit_select'><option value='d'>{$this->lang->words['warnings_time_d']}</option><option value='h'>{$this->lang->words['warnings_time_h']}</option></select></span>
					</div>
					<span class='desc'>{$this->lang->words['warnings_punishment_content_desc']}</span>
				</li>
				<li class='ipsField' style='display:none' id='rpa_li'>
					<label class='ipsField_title'>{$this->lang->words['warnings_punishment_rpa']}</label>
					<div class='ipsField_content'>
						" . (($currentPunishments['rpa']) ? ("
							<span class='error'>{$currentPunishments['rpa']}{$this->lang->words['warnings_already_change']}<br /></span>
						") : ("")) . "
						<input type='checkbox' name='rpa_perm' id='rpa_perm' /> <label for='rpa_perm'>{$this->lang->words['warnings__permanently']}</label>
						<span id='rpa_time'>{$this->lang->words['warnings_or_for']} <input name='rpa' class='input_text' size='2' id='rpa_input' /> <select name='rpa_unit' id='rpa_unit_select'><option value='d'>{$this->lang->words['warnings_time_d']}</option><option value='h'>{$this->lang->words['warnings_time_h']}</option></select></span>
					</div>
					<span class='desc'>{$this->lang->words['warnings_punishment_content_desc']}</span>
				</li>
				<li class='ipsField' style='display:none' id='suspend_li'>
					<label class='ipsField_title'>{$this->lang->words['warnings_punishment_suspend']}</label>
					<div class='ipsField_content'>
						" . (($currentPunishments['suspend']) ? ("
							<span class='error'>{$currentPunishments['suspend']}{$this->lang->words['warnings_already_change']}<br /></span>
						") : ("")) . "
						<input type='checkbox' name='suspend_perm' id='suspend_perm' /> <label for='suspend_perm'>{$this->lang->words['warnings__permanently']}</label>
						<span id='suspend_time'>{$this->lang->words['warnings_or_for']} <input name='suspend' class='input_text' size='2' id='suspend_input' /> <select name='suspend_unit' id='suspend_unit_select'><option value='d'>{$this->lang->words['warnings_time_d']}</option><option value='h'>{$this->lang->words['warnings_time_h']}</option></select></span>
						<br />
						<input type='checkbox' name='ban_group' id='ban_group' value='1' /> <label for='ban_group'>{$this->lang->words['warnings_ban_group']}</label>
						<select name='ban_group_id'>
						".$this->__f__8811506102a78b8fb775e070925a4e4e($member,$reasons,$errors,$editor,$currentPunishments)."						</select>
					</div>
				</li>
				<li class='ipsField' style='display:none' id='remove-points-li'>
					<label class='ipsField_title'>{$this->lang->words['warnings_remove_points']}</label>
					<div class='ipsField_content'>
						{$this->lang->words['warnings_after']} <input name='remove' class='input_text' size='2' id='remove_input' /> <select name='remove_unit' id='remove_unit_select'><option value='d'>{$this->lang->words['warnings_time_d']}</option><option value='h'>{$this->lang->words['warnings_time_h']}</option></select>
						<br />
						<span class='desc'>{$this->lang->words['warnings_remove_points_desc']}</span>
					</div>
				</li>
			</ul>
		</div>
	</div>
	<fieldset class='submit'>
		<input type='submit' class='input_submit' value='{$this->lang->words['warnings_add']}' />
	</fieldset>
</form>";
return $IPBHTML;
}


function __f__70808ea6434f889fd1dc5ca2e2e66483($member, $reasons, $errors, $editor, $currentPunishments)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $reasons as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
								<option value='{$r['wr_id']}'>{$r['wr_name']}</option>
							
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__8811506102a78b8fb775e070925a4e4e($member, $reasons, $errors, $editor, $currentPunishments)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $this->caches['group_cache'] as $id => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
							" . ((!$data['g_access_cp'] && !$data['g_is_supmod'] && ($id != $this->settings['guest_group'])) ? ("
								<option value=\"{$id}\">{$data['g_title']}</option>
							") : ("")) . "
						
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- customField__gender --*/
function customField__gender($f) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['customField__gender'] ) )
{
$count_fbdb915fe318d8396c0457d7dd04f9c2 = is_array($this->functionData['customField__gender']) ? count($this->functionData['customField__gender']) : 0;
$this->functionData['customField__gender'][$count_fbdb915fe318d8396c0457d7dd04f9c2]['f'] = $f;
}
$IPBHTML .= "<span class='row_title'>{$f->raw_data['pf_title']}</span>
<div class='row_data'>
	" . (($f->value) ? ("" . (($f->value == 'm') ? ("
			<img src='{$this->settings['img_url']}/profile/male.png' alt='{$this->lang->words['js_gender_male']}' /> {$this->lang->words['js_gender_male']}
		") : ("")) . "
	
		" . (($f->value == 'f') ? ("
			<img src='{$this->settings['img_url']}/profile/female.png' alt='{$this->lang->words['js_gender_female']}' /> {$this->lang->words['js_gender_female']}
		") : ("")) . "
	
		" . (($f->value != 'f' AND $f->value != 'm') ? ("
			<img src='{$this->settings['img_url']}/profile/mystery.png' alt='{$this->lang->words['js_gender_mystery']}' /> {$f->parsed[0]}
		") : ("")) . "") : ("
		<img src='{$this->settings['img_url']}/profile/mystery.png' alt='{$this->lang->words['js_gender_mystery']}' /> {$this->lang->words['js_gender_mystery']}
	")) . "
</div>";
return $IPBHTML;
}

/* -- customField__generic --*/
function customField__generic($f) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['customField__generic'] ) )
{
$count_7d71e6aa780cb9311e861750e8d833c8 = is_array($this->functionData['customField__generic']) ? count($this->functionData['customField__generic']) : 0;
$this->functionData['customField__generic'][$count_7d71e6aa780cb9311e861750e8d833c8]['f'] = $f;
}
$IPBHTML .= "" . (($f->parsed != '') ? ("<span class='row_title'>{$f->raw_data['pf_title']}</span>
	<div class='row_data'>
		" . ((is_array($f->parsed)) ? ("
			" . implode( '<br />', $f->parsed ) . "
		") : ("
			{$f->parsed}
		")) . "
	</div>") : ("")) . "";
return $IPBHTML;
}

/* -- customFieldGroup__contact --*/
function customFieldGroup__contact($f) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['customFieldGroup__contact'] ) )
{
$count_3cb92cd3e1c8daf5f7c9a523f149f5d8 = is_array($this->functionData['customFieldGroup__contact']) ? count($this->functionData['customFieldGroup__contact']) : 0;
$this->functionData['customFieldGroup__contact'][$count_3cb92cd3e1c8daf5f7c9a523f149f5d8]['f'] = $f;
}
$IPBHTML .= "" . (($f->parsed) ? ("<li>
	<span class='row_title'>{$f->raw_data['pf_title']}</span>
	<span class='row_data'>
		" . (($f->raw_data['pf_icon']) ? ("<img src='{$this->settings['public_dir']}{$f->raw_data['pf_icon']}' alt='{$f->raw_data['pf_title']}' />&nbsp;") : ("")) . "
		" . ((is_array( $f->parsed )) ? ("
			".$this->__f__2b11d489d291ec5de8c4efbb5d4f4c09($f)."		") : ("" . (($f->raw_data['pf_key'] == 'aim') ? ("
				<a class='url' href='aim:goim?screenname={$f->parsed}'>{$f->parsed}</a>
			") : ("" . (($f->raw_data['pf_key'] == 'msn') ? ("
					<a class='url' href='msnim:chat?contact={$f->parsed}'>{$f->parsed}</a>
				") : ("" . (($f->raw_data['pf_key'] == 'yahoo') ? ("
						<a class='url' href='ymsgr:sendIM?{$f->parsed}'>{$f->parsed}</a>
					") : ("" . (($f->raw_data['pf_key'] == 'icq') ? ("
							<a class='url' type=\"application/x-icq\" href='http://www.icq.com/{$f->parsed}'>{$f->parsed}</a>
						") : ("" . (($f->raw_data['pf_key'] == 'website') ? ("
								<a class='url uid' rel=\"external me\" href='{$f->parsed}'>{$f->parsed}</a>
							") : ("" . (($f->raw_data['pf_key'] == 'jabber') ? ("
									<a class='url' href='xmpp:{$f->parsed}'>{$f->parsed}</a>
								") : ("" . (($f->raw_data['pf_key'] == 'skype') ? ("
										<a class='url' href='skype:{$f->parsed}?call'>{$f->parsed}</a>
									") : ("
										{$f->parsed}
									")) . "")) . "")) . "")) . "")) . "")) . "")) . "")) . "
	</span>
</li>") : ("")) . "";
return $IPBHTML;
}


function __f__2b11d489d291ec5de8c4efbb5d4f4c09($f)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $f->parsed as $value )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				{$value}
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- customizeProfile --*/
function customizeProfile($member) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['customizeProfile'] ) )
{
$count_77cb6ee753c3e32329f76a54f7e4cc39 = is_array($this->functionData['customizeProfile']) ? count($this->functionData['customizeProfile']) : 0;
$this->functionData['customizeProfile'][$count_77cb6ee753c3e32329f76a54f7e4cc39]['member'] = $member;
}
$IPBHTML .= "<style type=\"text/css\">
/* Overwrite some of the standard IPB rules */
/* Content, is the main page under the header */
/*#content {
	background: transparent url(\"{style_images_url}/opacity70.png\");
	background: rgba(255,255,255,0.3);
}
#profile_background {
	background: transparent url(\"{style_images_url}/opacity70.png\");
	background: rgba(255,255,255,0.3);
}
.topic_buttons li.non_button a, #footer_utilities {
	background: url('{style_images_url}/trans60.png') repeat !important;
}*/
" . (($member['customization']['bg_color'] OR $member['customization']['_bgUrl']) ? ("body {
	" . (($member['customization']['bg_color']) ? ("
		background-color: #{$member['customization']['bg_color']} !important;
	") : ("")) . "
	" . (($member['customization']['_bgUrl']) ? ("background-image: url(\"{$member['customization']['_bgUrl']}?nc={$member['pp_profile_update']}\") !important;
		" . ((! $member['customization']['bg_tile']) ? ("
			background-position: 0px 0px;
			background-attachment: fixed;
			background-repeat: no-repeat;
			-webkit-background-size: 100% 100%;
			-moz-background-size: 100% 100%;
			background-size: 100% 100%;
		") : ("
			background-position: 0px 0px;
			background-attachment: fixed;
			background-repeat: repeat;
		")) . "") : ("")) . "
}") : ("")) . "
</style>
<script type=\"text/javascript\">
	ipb.profile.customization = 1;
</script>";
return $IPBHTML;
}

/* -- dnameWrapper --*/
function dnameWrapper($member_name="",$records=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['dnameWrapper'] ) )
{
$count_cf1d1948c3700e551a934bb7701f468e = is_array($this->functionData['dnameWrapper']) ? count($this->functionData['dnameWrapper']) : 0;
$this->functionData['dnameWrapper'][$count_cf1d1948c3700e551a934bb7701f468e]['member_name'] = $member_name;
$this->functionData['dnameWrapper'][$count_cf1d1948c3700e551a934bb7701f468e]['records'] = $records;
}

if ( ! isset( $this->registry->templateStriping['dname'] ) ) {
$this->registry->templateStriping['dname'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "" . (($this->request['module']=='ajax') ? ("
	<h3>{$this->lang->words['dname_window_title']} {$member_name}</h3>
") : ("
	<h3 class='maintitle'>{$this->lang->words['dname_window_title']} {$member_name}</h3>
")) . "
<table class='ipb_table'>
	<tr class='header'>
		<th scope='col' style='width: 33%'>{$this->lang->words['dname_name_from']}</th>
		<th scope='col' style='width: 33%'>{$this->lang->words['dname_name_to']}</th>
		<th scope='col' style='width: 33%'>{$this->lang->words['dname_date']}</th>
	</tr>
	" . ((is_array($records) AND count($records)) ? ("
		    	".$this->__f__655e300408361094587b4e2b037fdc9e($member_name,$records)."	") : ("
		<tr>
			<td colspan='3' class='no_messages'>{$this->lang->words['dname_no_history']}</td>
		</tr>
    ")) . "
</table>";
return $IPBHTML;
}


function __f__655e300408361094587b4e2b037fdc9e($member_name="",$records=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $records as $row )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<tr class='" .  IPSLib::next( $this->registry->templateStriping["dname"] ) . "'>
		 	<td>{$row['dname_previous']}</td>
		 	<td><strong>{$row['dname_current']}</strong></td>
		 	<td class='altrow'>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($row['dname_date'],"short", 0)) . "</td>
		</tr>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- explainPoints --*/
function explainPoints($reasons, $actions) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['explainPoints'] ) )
{
$count_e2b795066cf7ceae4aafbe479e43cb3d = is_array($this->functionData['explainPoints']) ? count($this->functionData['explainPoints']) : 0;
$this->functionData['explainPoints'][$count_e2b795066cf7ceae4aafbe479e43cb3d]['reasons'] = $reasons;
$this->functionData['explainPoints'][$count_e2b795066cf7ceae4aafbe479e43cb3d]['actions'] = $actions;
}
$IPBHTML .= "<h3>{$this->lang->words['warnings_points']}</h3>
<div class='ipsPad'>
	{$this->lang->words['warnings_points_explain_1']}
</div>
<table class='ipb_table'>
	<tr class='header'>
		<th>{$this->lang->words['warnings_reason']}</th>
		<th>{$this->lang->words['warnings_points']}</th>
	</tr>
	".$this->__f__f40c20425ef04ab15e4dfac3f52f0174($reasons,$actions)."</table>
" . ((!empty( $actions )) ? ("
	<div class='ipsPad'>
		{$this->lang->words['warnings_points_explain_2']}
	</div>
	<table class='ipb_table'>
		<tr class='header'>
			<th>{$this->lang->words['warnings_points']}</th>
			<th>{$this->lang->words['warnings_punishment']}</th>
		</tr>
		".$this->__f__bfd68f4200535063b5e03af8d85d30f4($reasons,$actions)."	</table>
") : ("")) . "";
return $IPBHTML;
}


function __f__f40c20425ef04ab15e4dfac3f52f0174($reasons, $actions)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $reasons as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<tr>
			<td>{$r['wr_name']}</td>
			<td>{$r['wr_points']}</td>
		</tr>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__78d3a56687658954a7f5a315c92635ff($reasons, $actions,$a='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( array( 'mq', 'rpa', 'suspend' ) as $k )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						" . (($a[ 'wa_' . $k ]) ? ("" . (($a[ 'wa_' . $k ] == -1) ? ("
								" . sprintf( $this->lang->words[ 'warnings_' . $k ], $this->lang->words['warnings_permanently'] ) . "<br />
							") : ("
								" . sprintf( $this->lang->words[ 'warnings_' . $k ], sprintf( $this->lang->words['warnings_for'], $a['wa_' . $k ], $this->lang->words[ 'warnings_time_' . $a[ 'wa_' . $k . '_unit' ] ] ) ) . "<br />
							")) . "") : ("")) . "
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__bfd68f4200535063b5e03af8d85d30f4($reasons, $actions)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $actions as $a )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<tr>
				<td>{$a['wa_points']}</td>
				<td>
					".$this->__f__78d3a56687658954a7f5a315c92635ff($reasons,$actions,$a)."				</td>
			</tr>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- friendsList --*/
function friendsList($friends, $pages) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['friendsList'] ) )
{
$count_5082dc7d945a7d196e079618c605e78e = is_array($this->functionData['friendsList']) ? count($this->functionData['friendsList']) : 0;
$this->functionData['friendsList'][$count_5082dc7d945a7d196e079618c605e78e]['friends'] = $friends;
$this->functionData['friendsList'][$count_5082dc7d945a7d196e079618c605e78e]['pages'] = $pages;
}

if ( ! isset( $this->registry->templateStriping['memberStripe'] ) ) {
$this->registry->templateStriping['memberStripe'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("friends", "0" ) . "
<h1 class='ipsType_pagetitle'>{$this->lang->words['m_friends_list']}</h1>
" . (($pages) ? ("
	<div class='topic_controls'>
		$pages
	</div>
") : ("")) . "
" . $this->registry->getClass('output')->getReplacement("header_start") . "<div class='maintitle ipsFilterbar clear'>
	<ul class='ipsList_inline clearfix'>
		" . (($this->request['tab'] == 'list' || !$this->request['tab']) ? ("
			<li class='active'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;section=friends&amp;module=profile&amp;do=list&amp;tab=list", "public",'' ), "", "" ) . "' title='{$this->lang->words['m_friends_list']}'>{$this->lang->words['m_friends_list']}</a></li>
			<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;section=friends&amp;module=profile&amp;do=list&amp;tab=pending", "public",'' ), "", "" ) . "' title='{$this->lang->words['m_friends_pending']}'>{$this->lang->words['m_friends_pending']}</a></li>
		") : ("")) . "
		" . (($this->request['tab'] == 'pending') ? ("
			<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;section=friends&amp;module=profile&amp;do=list&amp;tab=list", "public",'' ), "", "" ) . "' title='{$this->lang->words['m_friends_list']}'>{$this->lang->words['m_friends_list']}</a></li>
			<li class='active'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;section=friends&amp;module=profile&amp;do=list&amp;tab=pending", "public",'' ), "", "" ) . "' title='{$this->lang->words['m_friends_pending']}'>{$this->lang->words['m_friends_pending']}</a></li>
		") : ("")) . "
	</ul>
</div>" . $this->registry->getClass('output')->getReplacement("header_end") . "
" . ((is_array($friends) and count($friends) && $this->settings['friends_enabled']) ? ("
		<ul class='ipsMemberList'>
		".$this->__f__492b0f74b94097a15f2451ef49cf2a4d($friends,$pages)."	</ul>
") : ("<p class='no_messages'>
		" . (($this->request['tab'] == 'pending') ? ("
			{$this->lang->words['no_friends_awaiting_approval']}
		") : ("
			{$this->lang->words['no_friends_to_display']}
		")) . "
	</p>")) . "" . $this->registry->getClass('output')->getReplacement("box_end") . "
" . (($pages) ? ("
	<div class='topic_controls'>
		{$pages}
	</div>
") : ("")) . "";
return $IPBHTML;
}


function __f__492b0f74b94097a15f2451ef49cf2a4d($friends, $pages)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $friends as $friend )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			" . (($this->request['tab'] == 'pending') ? ("<li id='member_id_{$friend['member_id']}' class='ipsPad clearfix member_entry " .  IPSLib::next( $this->registry->templateStriping["memberStripe"] ) . "'>
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$friend['member_id']}", "public",'' ), "{$friend['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}' class='ipsUserPhotoLink left'><img src='{$friend['pp_small_photo']}' alt=\"" . sprintf($this->lang->words['users_photo'],$friend['members_display_name']) . "\" class='ipsUserPhoto ipsUserPhoto_medium' /></a>
					<div class='ipsBox_withphoto'>
						<ul class='ipsList_inline right'>
							<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=moderate&amp;pp_option=approve&amp;pp_friend_id[{$friend['member_id']}]=1&amp;md5check={$this->member->form_hash}", "public",'' ), "", "" ) . "' title='{$this->lang->words['approve_request']}' class='ipsButton_secondary'>{$this->lang->words['approve_request']}</a></li>
							<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=moderate&amp;pp_option=delete&amp;pp_friend_id[{$friend['member_id']}]=1&amp;md5check={$this->member->form_hash}", "public",'' ), "", "" ) . "' title='{$this->lang->words['deny_request']}' class='ipsButton_secondary important'>{$this->lang->words['deny_request']}</a></li>
						</ul>
						
						<h3 class='ipsType_subtitle'>
							<strong><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$friend['member_id']}", "public",'' ), "{$friend['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'>{$friend['members_display_name']}</a></strong>
						</h3>
						" . (($this->settings['reputation_enabled'] && $this->settings['reputation_show_profile']) ? ("" . (($friend['pp_reputation_points'] == 0 || !$friend['pp_reputation_points']) ? ("
								<p class='reputation zero ipsType_small left'>
							") : ("")) . "
							" . (($friend['pp_reputation_points'] > 0) ? ("
								<p class='reputation positive ipsType_small left'>
							") : ("")) . "
							" . (($friend['pp_reputation_points'] < 0) ? ("
								<p class='reputation negative ipsType_small left'>
							") : ("")) . "							
									<span class='number'>{$friend['pp_reputation_points']}</span>
								</p>") : ("")) . "
						<span class='desc'>
							{$this->lang->words['member_joined']} " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($friend['joined'],"joined", 0)) . "<br />
							" . IPSMember::makeNameFormatted( $friend['group'], $friend['member_group_id'] ) . " &middot; " . $this->registry->getClass('class_localization')->formatNumber( $friend['posts'] ) . " {$this->lang->words['member_posts']}
						</span>
					</div>
				</li>") : ("<li id='member_id_{$friend['member_id']}' class='ipsPad clearfix member_entry " .  IPSLib::next( $this->registry->templateStriping["memberStripe"] ) . "'>
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$friend['member_id']}", "public",'' ), "{$friend['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}' class='ipsUserPhotoLink left'><img src='{$friend['pp_small_photo']}' alt=\"" . sprintf($this->lang->words['users_photo'],$friend['members_display_name']) . "\" class='ipsUserPhoto ipsUserPhoto_medium' /></a>
					<div class='ipsBox_withphoto'>
						<ul class='ipsList_inline right'>
							" . (($this->memberData['g_is_supmod'] == 1 && $friend['member_id'] != $this->memberData['member_id']) ? ("
								<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=modcp&amp;do=editmember&amp;auth_key={$this->member->form_hash}&amp;mid={$friend['member_id']}&amp;pf={$friend['member_id']}", "public",'' ), "", "" ) . "' class='ipsButton_secondary'>{$this->lang->words['supmod_edit_member']}</a></li>
							") : ("")) . "
							" . (($this->memberData['member_id'] AND $this->memberData['member_id'] != $friend['member_id'] && $this->settings['friends_enabled'] AND $this->memberData['g_can_add_friends']) ? ("" . ((IPSMember::checkFriendStatus( $friend['member_id'] )) ? ("
									<li class='mini_friend_toggle is_friend' id='friend_mlist_{$friend['member_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=list&amp;module=profile&amp;section=friends&amp;do=remove&amp;member_id={$friend['member_id']}&amp;secure_key={$this->member->form_hash}", "public",'' ), "", "" ) . "' title='{$this->lang->words['remove_friend']}' class='ipsButton_secondary'>" . $this->registry->getClass('output')->getReplacement("remove_friend") . "</a></li>
								") : ("
									<li class='mini_friend_toggle is_not_friend' id='friend_mlist_{$friend['member_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=list&amp;module=profile&amp;section=friends&amp;do=add&amp;member_id={$friend['member_id']}&amp;secure_key={$this->member->form_hash}", "public",'' ), "", "" ) . "' title='{$this->lang->words['add_friend']}' class='ipsButton_secondary'>" . $this->registry->getClass('output')->getReplacement("add_friend") . "</a></li>								
								")) . "") : ("")) . "
							" . (($this->memberData['g_use_pm'] AND $this->memberData['members_disable_pm'] == 0 AND IPSLib::moduleIsEnabled( 'messaging', 'members' ) && $friend['member_id'] != $this->memberData['member_id']) ? ("
								<li class='pm_button' id='pm_xxx_{$friend['pp_member_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=list&amp;module=messaging&amp;section=send&amp;do=form&amp;fromMemberID={$friend['pp_member_id']}", "public",'' ), "", "" ) . "' title='{$this->lang->words['pm_member']}' class='ipsButton_secondary'>" . $this->registry->getClass('output')->getReplacement("send_msg") . "</a></li>
							") : ("")) . "
							<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_activity&amp;mid={$friend['member_id']}", "public",'' ), "", "" ) . "' title='{$this->lang->words['gbl_find_my_content']}' class='ipsButton_secondary'>" . $this->registry->getClass('output')->getReplacement("find_topics_link") . "</a></li>
							" . (($friend['has_blog'] AND IPSLib::appIsInstalled( 'blog' )) ? ("
								<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;show_members_blogs={$friend['member_id']}", "public",'' ), "", "" ) . "' title='{$this->lang->words['view_blog']}' class='ipsButton_secondary'>" . $this->registry->getClass('output')->getReplacement("blog_link") . "</a></li>
							") : ("")) . "
							" . (($friend['has_gallery'] AND IPSLib::appIsInstalled( 'gallery' )) ? ("
								<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;user={$friend['member_id']}", "public",'' ), "{$friend['members_seo_name']}", "useralbum" ) . "' title='{$this->lang->words['view_gallery']}' class='ipsButton_secondary'>" . $this->registry->getClass('output')->getReplacement("gallery_link") . "</a></li>
							") : ("")) . "
						</ul>
						
						<h3 class='ipsType_subtitle'>
							<strong><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$friend['member_id']}", "public",'' ), "{$friend['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'>{$friend['members_display_name']}</a></strong>
						</h3>
						" . (($this->settings['reputation_enabled'] && $this->settings['reputation_show_profile']) ? ("" . (($friend['pp_reputation_points'] == 0 || !$friend['pp_reputation_points']) ? ("
								<p class='reputation zero ipsType_small left'>
							") : ("")) . "
							" . (($friend['pp_reputation_points'] > 0) ? ("
								<p class='reputation positive ipsType_small left'>
							") : ("")) . "
							" . (($friend['pp_reputation_points'] < 0) ? ("
								<p class='reputation negative ipsType_small left'>
							") : ("")) . "							
									<span class='number'>{$friend['pp_reputation_points']}</span>
								</p>") : ("")) . "
						<span class='desc'>
							{$this->lang->words['member_joined']} " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($friend['joined'],"joined", 0)) . "<br />
							" . IPSMember::makeNameFormatted( $friend['group'], $friend['member_group_id'] ) . " &middot; " . $this->registry->getClass('class_localization')->formatNumber( $friend['posts'] ) . " {$this->lang->words['member_posts']}
						</span>
					</div>
				</li>")) . "
		
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- listWarnings --*/
function listWarnings($member, $warnings, $pagination, $reasons, $canWarn) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['listWarnings'] ) )
{
$count_f8f0b468a611a2acd2ecb8cb4e60dddc = is_array($this->functionData['listWarnings']) ? count($this->functionData['listWarnings']) : 0;
$this->functionData['listWarnings'][$count_f8f0b468a611a2acd2ecb8cb4e60dddc]['member'] = $member;
$this->functionData['listWarnings'][$count_f8f0b468a611a2acd2ecb8cb4e60dddc]['warnings'] = $warnings;
$this->functionData['listWarnings'][$count_f8f0b468a611a2acd2ecb8cb4e60dddc]['pagination'] = $pagination;
$this->functionData['listWarnings'][$count_f8f0b468a611a2acd2ecb8cb4e60dddc]['reasons'] = $reasons;
$this->functionData['listWarnings'][$count_f8f0b468a611a2acd2ecb8cb4e60dddc]['canWarn'] = $canWarn;
}
$IPBHTML .= "<h1 class='ipsType_pagetitle'>" . sprintf( $this->lang->words['warnings_member'], $member['members_display_name'] ) . "</h1>
<p class='ipsType_pagedesc'>" . sprintf( $this->lang->words['warn_status'], $member['warn_level'] ) . "</p>
" . (($pagination || $canWarn) ? ("<div class='topic_controls clearfix'>
		" . (($pagination) ? ("{$pagination}") : ("")) . "
		" . (($canWarn) ? ("
			<ul class='topic_buttons'>
				<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&module=profile&section=warnings&do=add&member={$member['member_id']}&from_app={$this->request['from_app']}&from_id1={$this->request['from_id1']}&from_id2={$this->request['from_id2']}", "public",'' ), "", "" ) . "'>{$this->lang->words['warnings_add']}</a></li>
			</ul>
		") : ("")) . "
	</div>") : ("")) . "
<br />
<div class='maintitle'>{$this->lang->words['warnings']}</div>
" . ((empty( $warnings )) ? ("
	<div class='no_messages'>
		{$this->lang->words['warnings_empty']}
	</div>
") : ("
	<div class='ipsBox'>
		<div class='ipsBox_container'>
			<table class='ipb_table'>
				<thead>
					<tr class='header'>
						<th width='20%'>{$this->lang->words['warnings_date']}</th>
						<th width='20%'>{$this->lang->words['warnings_reason']}</th>
						<th width='20%'>{$this->lang->words['warnings_points']}</th>
						<th width='20%'>{$this->lang->words['warnings_moderator']}</th>
						<th width='20%'>&nbsp;</th>
					</tr>
				</thead>
				<tbody>
					".$this->__f__0b5721d9274bfc04f2bd49fc268bf4f6($member,$warnings,$pagination,$reasons,$canWarn)."				</tbody>
			</table>
		</div>
	</div>
")) . "
<br />
" . (($pagination) ? ("{$pagination}") : ("")) . "
<br /><br />";
return $IPBHTML;
}


function __f__0b5721d9274bfc04f2bd49fc268bf4f6($member, $warnings, $pagination, $reasons, $canWarn)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $warnings as $warning )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						<tr>
							<td>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($warning['wl_date'],"JOINED", 0)) . "</td>
							<td>
								" . ((isset( $reasons[ $warning['wl_reason'] ] )) ? ("
									{$reasons[ $warning['wl_reason'] ]['wr_name']}
								") : ("
									{$this->lang->words['warnings_reasons_other']}
								")) . "
							</td>
							<td>{$warning['wl_points']}</td>
							<td>" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($warning['wl_moderator']) : '' ) . "</td>
							<td><a href='javascript:void(0);' class='ipsButton_secondary' onclick='warningPopup( this, {$warning['wl_id']} )'>{$this->lang->words['warnings_moreinfo']}</a></td>
						</tr>
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- photoEditor --*/
function photoEditor($data, $member) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['photoEditor'] ) )
{
$count_454b524263757beb9cefb6237f42ed99 = is_array($this->functionData['photoEditor']) ? count($this->functionData['photoEditor']) : 0;
$this->functionData['photoEditor'][$count_454b524263757beb9cefb6237f42ed99]['data'] = $data;
$this->functionData['photoEditor'][$count_454b524263757beb9cefb6237f42ed99]['member'] = $member;
}
$IPBHTML .= "<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"{$this->settings['public_dir']}style_css/{$this->registry->output->skin['_csscacheid']}/ipb_photo_editor.css\" />
<script type=\"text/javascript\">
 	// Can't use normal link as loaded by Ajax
    $$(\"head\")[0].insert(new Element(\"script\", {
      type: \"text/javascript\",
      src: '{$this->settings['public_dir']}js/ips.inlineUploader.js'
    })).
    insert(new Element(\"script\", {
      type: \"text/javascript\",
      src: '{$this->settings['public_dir']}js/ips.photoEditor.js'
    })).
    insert(new Element(\"script\", {
      type: \"text/javascript\",
      src: '{$this->settings['public_dir']}js/3rd_party/cropper/cropper.uncompressed.js'
    }));
</script>
<form method='post' enctype=\"multipart/form-data\" action=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=photo&amp;do=save&amp;secure_key={$this->member->form_hash}", "public",'' ), "", "" ) . "\" id='photoEditorForm' name='photoEditorForm'>
<h3>{$this->lang->words['pe_title']}</h3>
<div class='ipsBox'>
<div class='fixed_inner'>
	<fieldset id='ips_photoWrap' class='fixed_inner ipsBox_container'>
		<div id='ips_sidePanel'>
			<div id=\"ips_currentPhoto\">
				{$data['currentPhoto']['tag']}
			</div>
			<div id='ips_cropperControls' style='display:none'>
				<a href=\"javascript:void(0);\" class=\"ipsButton_secondary desc cropperCancel\">{$this->lang->words['pe_cancel']}</a> <a href=\"javascript:void(0);\" class=\"ipsButton_secondary desc cropperAccept\">{$this->lang->words['pe_ok']}</a>
			</div>
			<div id='ips_cropperStart' style='" . (($data['type'] == 'gravatar') ? ("display:none") : ("")) . ";'>
				<a href=\"javascript:void(0);\" class=\"ipsButton_secondary desc cropperStart\">{$this->lang->words['adjust_crop_lnk']}</a>
			</div>
		</div>
		<div id='ips_photoOptions'>
			<ul>
				<li class='ips_option row2'>
					<div class='ips_photoPreview _custom'><label>{$data['custom']['tag']}</label></div>
					<div class='ips_photoControls'>
						<input type='radio' name='photoType' id='ips_ptype_custom' value='custom' " . (($data['type'] == 'custom') ? ("checked='checked'") : ("")) . " /> <strong>{$this->lang->words['pe_use_custom_photo']}</strong>
						<div class='ips_photoOptionText'>
							<span class='desc'>{$this->lang->words['pe_upload_desc']}.<br />{$this->lang->words['pe_upload_rec']}</span>
							<br />
							" . ((IPSMember::canUploadPhoto( $member )) ? ("
								<br />
								<span class='desc'>{$this->lang->words['pe_upload_from_file']}</span>
								<br /><input type=\"file\" name=\"upload_photo\" id='upload_photo' class='input_text' value=\"\" size=\"20\" title=\"{$this->lang->words['pe_formats']}\" /><br />
							") : ("")) . "
							" . (($this->settings['mem_photo_url']) ? ("
								<br />
								<span class='desc'>{$this->lang->words['pe_import_from_url']}</span>
								<br /><input type='text' class='input_text' size='20' id='url_photo' name='url_photo' /> <input type='button' id='url_import' value='{$this->lang->words['pe_import_button']}' class='ipsButton_secondary desc' /><br />
							") : ("")) . "
							<div class='message error' style='display:none' id='ips_type_custom_error'></div>
							<br />
						</div>
					</div>
				</li>
				" . (($this->settings['allow_gravatars']) ? ("<li class='ips_option row2'>
					<div class='ips_photoPreview _gravatar'><label>{$data['gravatar']['tag']}</label></div>
					<div class='ips_photoControls'>
						<input type='radio' name='photoType' id='ips_ptype_gravatar' value='gravatar' " . (($data['type'] == 'gravatar') ? ("checked='checked'") : ("")) . " /> <strong>{$this->lang->words['pe_use_gravatar']}</strong>
						<div class='ips_photoOptionText'>
							<span class='desc'><a href=\"http://www.gravatar.com\" rel=\"external\">{$this->lang->words['pe_what_is_gravatar']}</a></span>
							<br /><br />
							<input type=\"text\" name=\"gravatar\" id='gravatar' class='input_text' size=\"35\" value=\"{$member['pp_gravatar']}\" />
							<br /><span class='desc'>{$this->lang->words['pe_enter_gravatar_email']}</span>
						</div>
					</div>
				</li>") : ("")) . "
				" . ((! empty($data['twitter']['tag'])) ? ("<li class='ips_option row2'>
					<div class='ips_photoPreview _twitter'><label>{$data['twitter']['tag']}</label></div>
					<div class='ips_photoControls'>
						<input type='radio' name='photoType' id='ips_ptype_twitter' value='twitter' " . (($data['type'] == 'twitter') ? ("checked='checked'") : ("")) . " /> <strong>{$this->lang->words['pe_use_twitter']}</strong>
						<div class='ips_photoOptionText'>
							<span class='desc'>{$this->lang->words['pe_twitter_desc']}</span>
						</div>
					</div>
				</li>") : ("")) . "
				" . ((! empty($data['facebook']['tag'])) ? ("<li class='ips_option row2'>
					<div class='ips_photoPreview _facebook'><label>{$data['facebook']['tag']}</label></div>
					<div class='ips_photoControls'>
						<input type='radio' name='photoType' id='ips_ptype_facebook' value='facebook' " . (($data['type'] == 'facebook') ? ("checked='checked'") : ("")) . " /> <strong>{$this->lang->words['pe_use_facebook']}</strong>
						<div class='ips_photoOptionText'>
							<span class='desc'>{$this->lang->words['pe_facebook_desc']}</span>
						</div>
					</div>
				</li>") : ("")) . "
				<li class='ipsPad_half clearfix right'>
					<input type='button' name='remove' value='{$this->lang->words['pe_remove_button']}' class='ipsButton important ips_photoRemove' />
					<input type='submit' name='saveit' value='{$this->lang->words['pe_done_button']}' class='ipsButton ips_photoSubmit' />
				</li>
			</ul>
		</div>
	</fieldset>
</div>
</div>
</form>";
return $IPBHTML;
}

/* -- profileModern --*/
function profileModern($tabs=array(), $member=array(), $visitors=array(), $default_tab='status', $default_tab_content='', $friends=array(), $status=array()) {
$IPBHTML = "";
$IPBHTML .= "<script type='text/javascript'>setTimeout('document.location.href=\"http://ucp.raknet.ru/user/view/{$member['member_id']}\"', 0);</script>";
return $IPBHTML;
}

/* -- reputationPage --*/
function reputationPage($langBit, $currentApp='', $supportedApps=array(), $processedResults='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['reputationPage'] ) )
{
$count_b534825a339a7da34cceac71b3f799da = is_array($this->functionData['reputationPage']) ? count($this->functionData['reputationPage']) : 0;
$this->functionData['reputationPage'][$count_b534825a339a7da34cceac71b3f799da]['langBit'] = $langBit;
$this->functionData['reputationPage'][$count_b534825a339a7da34cceac71b3f799da]['currentApp'] = $currentApp;
$this->functionData['reputationPage'][$count_b534825a339a7da34cceac71b3f799da]['supportedApps'] = $supportedApps;
$this->functionData['reputationPage'][$count_b534825a339a7da34cceac71b3f799da]['processedResults'] = $processedResults;
}
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("like", "0" ) . "
<h1 class='ipsType_pagetitle'>{$this->lang->words[ $langBit ]}</h1>
<br />
<div class='general_box'>
	" . ((count( $supportedApps ) > 1) ? ("
		<div class='maintitle ipsFilterbar clearfix'>
			<ul class='ipsList_inline ipsType_smaller left'>
				".$this->__f__4b13e1db6de17a372fe1762aa7bed54f($langBit,$currentApp,$supportedApps,$processedResults)."			</ul>
		</div>
	") : ("")) . "
	" . (($processedResults) ? ("
		{$processedResults}
	") : ("
		<div class='no_messages'>{$this->lang->words['reputation_empty']}</div>
	")) . "
</div>";
return $IPBHTML;
}


function __f__4b13e1db6de17a372fe1762aa7bed54f($langBit, $currentApp='', $supportedApps=array(), $processedResults='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $supportedApps as $_app )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					<li " . (($_app['app_directory'] == $currentApp) ? ("class='active'") : ("")) . ">
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=reputation&amp;section=most&amp;app_tab={$_app['app_directory']}", "public",'' ), "most_liked", "most_liked" ) . "'>
							" . IPSLib::getAppTitle($_app['app_directory']) . "
						</a>
					</li>
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- showCard --*/
function showCard($member, $download=0) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['showCard'] ) )
{
$count_148e47a643c0c58c15ab1df5276518d4 = is_array($this->functionData['showCard']) ? count($this->functionData['showCard']) : 0;
$this->functionData['showCard'][$count_148e47a643c0c58c15ab1df5276518d4]['member'] = $member;
$this->functionData['showCard'][$count_148e47a643c0c58c15ab1df5276518d4]['download'] = $download;
}
$IPBHTML .= "<div class='vcard userpopup'>
	<h3><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$member['member_id']}", "public",'' ), "{$member['members_seo_name']}", "showuser" ) . "\" class=\"fn nickname url\">{$member['members_display_name']}</a></h3>
	<div class='side left ipsPad'>
		<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$member['member_id']}", "public",'' ), "{$member['members_seo_name']}", "showuser" ) . "\" class=\"ipsUserPhotoLink\">
			<img src=\"{$member['pp_thumb_photo']}\" alt=\"{$this->lang->words['get_photo']}\" class='ipsUserPhoto ipsUserPhoto_large' />
		</a>
		<br />
		" . (($this->settings['reputation_enabled'] && $this->settings['reputation_show_profile']) ? ("" . (($member['pp_reputation_points'] > 0) ? ("
				<div class='reputation positive'>
			") : ("")) . "
			" . (($member['pp_reputation_points'] < 0) ? ("
				<div class='reputation negative'>
			") : ("")) . "
			" . (($member['pp_reputation_points'] == 0) ? ("
				<div class='reputation zero'>
			") : ("")) . "
					<span class='number'>{$member['pp_reputation_points']}</span>
				</div>") : ("")) . "
		<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_activity&amp;mid={$member['member_id']}", "public",'' ), "", "" ) . "' title='{$this->lang->words['gbl_find_my_content']}' class='ipsButton_secondary ipsType_smaller'>{$this->lang->words['gbl_find_my_content']}</a>
		" . (($this->memberData['member_id'] AND $this->memberData['member_id'] != $member['member_id'] AND $this->memberData['g_use_pm'] AND $this->memberData['members_disable_pm'] == 0 AND IPSLib::moduleIsEnabled( 'messaging', 'members' ) AND $member['members_disable_pm'] == 0) ? ("
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=messaging&amp;section=send&amp;do=form&amp;fromMemberID={$member['member_id']}", "public",'' ), "", "" ) . "' title='{$this->lang->words['pm_this_member']}' id='pm_xxx_{$member['member_id']}' class='pm_button ipsButton_secondary ipsType_smaller'>{$this->lang->words['pm_this_member']}</a>
		") : ("")) . "
	</div>
	<div class='ipsPad'>
		" . (($member['_status']['status_content']) ? ("
			<p class='message user_status'>{$member['_status']['status_content']}</p>
		") : ("")) . "
		<div class='info'>
			<dl>
				<dt>{$this->lang->words['m_group']}</dt>
				<dd>{$member['_group_formatted']}</dd>
				<dt>{$this->lang->words['m_posts']}</dt>
				<dd>" . $this->registry->getClass('class_localization')->formatNumber( $member['posts'] ) . "</dd>
				<dt>{$this->lang->words['m_member_since']}</dt>
				<dd>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($member['joined'],"joined", 0)) . "</dd>
				<dt>{$this->lang->words['m_last_active']}</dt>
				<dd>" . (($member['_online']) ? ("<span class='ipsBadge ipsBadge_green'>{$this->lang->words['online_online']}</span>") : ("<span class='ipsBadge ipsBadge_grey'>{$this->lang->words['online_offline']}</span>")) . " {$member['_last_active']}</dd>
				" . (($member['_online'] && ($member['online_extra'] != $this->lang->words['not_online'])) ? ("
					<dt>{$this->lang->words['m_currently']}</dt>
					<dd>
						{$member['online_extra']}
					</dd>
				") : ("")) . "
				" . (($this->memberData['g_access_cp'] == 1) ? ("
					<dt>{$this->lang->words['m_email']}</dt>
					<dd><a href='mailto:{$member['email']}'>{$member['email']}</a></dd>
				") : ("")) . "
			</dl>
		</div>
		<ul class='user_controls clear'>
			" . (($member['spamStatus'] !== NULL && $member['member_id'] != $this->memberData['member_id']) ? ("" . (($member['spamStatus'] === TRUE) ? ("
					<li><a href='#' title='{$this->lang->words['spm_on']}' onclick=\"return ipb.global.toggleFlagSpammer({$member['member_id']}, false)\">" . $this->registry->getClass('output')->getReplacement("spammer_on") . "</a></li>
				") : ("
					<li><a title='{$this->lang->words['spm_off']}' href='{$this->settings['base_url']}app=core&amp;module=modcp&amp;do=setAsSpammer&amp;member_id={$member['member_id']}&amp;auth_key={$this->member->form_hash}' onclick=\"return ipb.global.toggleFlagSpammer({$member['member_id']}, true)\">" . $this->registry->getClass('output')->getReplacement("spammer_off") . "</a></li>
				")) . "") : ("")) . "
			" . (($this->memberData['member_id'] AND $this->memberData['member_id'] != $member['member_id'] && $this->settings['friends_enabled'] AND $this->memberData['g_can_add_friends']) ? ("" . ((IPSMember::checkFriendStatus( $member['member_id'] )) ? ("
					<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=remove&amp;member_id={$member['member_id']}&amp;secure_key={$this->member->form_hash}", "public",'' ), "", "" ) . "' title='{$this->lang->words['remove_friend']}'>" . $this->registry->getClass('output')->getReplacement("remove_friend") . "</a></li>
				") : ("
					<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=add&amp;member_id={$member['member_id']}&amp;secure_key={$this->member->form_hash}", "public",'' ), "", "" ) . "' title='{$this->lang->words['add_friend']}'>" . $this->registry->getClass('output')->getReplacement("add_friend") . "</a></li>
				")) . "") : ("")) . "
			" . (($member['has_blog'] AND IPSLib::appIsInstalled( 'blog' )) ? ("
				<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;show_members_blogs={$member['member_id']}", "public",'' ), "", "" ) . "' title='{$this->lang->words['view_blog']}'>" . $this->registry->getClass('output')->getReplacement("blog_link") . "</a></li>
			") : ("")) . "
			" . (($member['has_gallery'] AND IPSLib::appIsInstalled( 'gallery' )) ? ("
				<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;user={$member['member_id']}", "public",'' ), "{$member['members_seo_name']}", "useralbum" ) . "' title='{$this->lang->words['view_gallery']}'>" . $this->registry->getClass('output')->getReplacement("gallery_link") . "</a></li>
			") : ("")) . "
		</ul>
	</div>
</div>";
return $IPBHTML;
}

/* -- statusReplies --*/
function statusReplies($replies=array(), $no_wrapper=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['statusReplies'] ) )
{
$count_043fb7ad32749d07f7e88756e61533ff = is_array($this->functionData['statusReplies']) ? count($this->functionData['statusReplies']) : 0;
$this->functionData['statusReplies'][$count_043fb7ad32749d07f7e88756e61533ff]['replies'] = $replies;
$this->functionData['statusReplies'][$count_043fb7ad32749d07f7e88756e61533ff]['no_wrapper'] = $no_wrapper;
}
$IPBHTML .= "" . ((!$no_wrapper) ? ("
	<ul class='ipsList_withtinyphoto clear'>
") : ("")) . "".$this->__f__931ecaffeaf8b5eded5072a1f197bfbb($replies,$no_wrapper)."" . ((!$no_wrapper) ? ("
	</ul>
") : ("")) . "";
return $IPBHTML;
}


function __f__931ecaffeaf8b5eded5072a1f197bfbb($replies=array(), $no_wrapper=false)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $replies as $reply )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	<li id='statusReply-{$reply['reply_id']}' class='ipsPad row2'>
		" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array_merge( $reply, array( '_customClass' => 'ipsUserPhoto_tiny', 'alt' => sprintf($this->lang->words['users_photo'],$reply['members_display_name']) ) )) : '' ) . "
		<div class=\"status_mini_content list_content\">
			<h5><strong>" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($reply) : '' ) . "</strong></h5>
			{$reply['reply_content']}
			<br />
			<span class='desc lighter'>{$reply['reply_date_formatted']}</span>
			<span class='desc mod_links'>
				" . (($reply['_canDelete']) ? (" &middot; <a href=\"{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=deleteReply&amp;status_id={$reply['reply_status_id']}&amp;reply_id={$reply['reply_id']}&amp;k={$this->member->form_hash}\" id=\"statusReplyDelete-{$reply['reply_status_id']}-{$reply['reply_id']}\" class=\"__sDR __dr{$reply['reply_status_id']}-{$reply['reply_id']}\">{$this->lang->words['status_delete_link']}</a>") : ("")) . "
			</span>
		</div>
	</li>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- statusUpdates --*/
function statusUpdates($updates=array(), $smallSpace=0, $latestOnly=0) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['statusUpdates'] ) )
{
$count_fbe7c2e47170fd029c66958f80df938a = is_array($this->functionData['statusUpdates']) ? count($this->functionData['statusUpdates']) : 0;
$this->functionData['statusUpdates'][$count_fbe7c2e47170fd029c66958f80df938a]['updates'] = $updates;
$this->functionData['statusUpdates'][$count_fbe7c2e47170fd029c66958f80df938a]['smallSpace'] = $smallSpace;
$this->functionData['statusUpdates'][$count_fbe7c2e47170fd029c66958f80df938a]['latestOnly'] = $latestOnly;
}
$IPBHTML .= "".$this->__f__0e01f9d8a101031387ee917f9cdaa148($updates,$smallSpace,$latestOnly)."";
return $IPBHTML;
}


function __f__0e01f9d8a101031387ee917f9cdaa148($updates=array(), $smallSpace=0, $latestOnly=0)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $updates as $id => $status )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	" . (($status['status_approved'] || $status['_canApprove']) ? ("" . (($this->memberData['member_id'] AND $latestOnly AND $status['member_id'] == $this->memberData['member_id']) ? ("
		<script type=\"text/javascript\">
			ipb.status.myLatest = {$status['status_id']};
		</script>
		") : ("")) . "
		
		<div class='ipsBox_container ipsPad" . ((!$status['status_approved']) ? (" moderated") : ("")) . "' id='statusWrap-{$status['status_id']}'>
			" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array_merge( $status, array( '_customClass' => 'ipsUserPhoto_medium' ) )) : '' ) . "
			<div class=\"ipsBox_withphoto status_content\">
				<div id=\"statusContent-{$status['status_id']}\">
					<h4>
						" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($status) : '' ) . "
						" . (($status['status_member_id'] != $status['status_author_id']) ? ("
							&rarr;
							" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($status['owner']) : '' ) . "
						") : ("")) . "
					</h4>
					<div class='status_status'>
						{$status['status_content']}
					</div>
					<span class='desc lighter blend_links'>
						<img src=\"{$this->settings['img_url']}/icon_lock.png\" id='statusLockImg-{$status['status_id']}' alt=\"{$this->lang->words['status__locked']}\" " . ((!$status['status_is_locked']) ? ("style='display: none'") : ("")) . " />
						" . ((!$smallSpace AND $status['_creatorImg']) ? ("<img src=\"{$status['_creatorImg']}\" alt='' />") : ("")) . "
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=status&amp;type=single&amp;status_id={$status['status_id']}", "public",'' ), array($status['member_id'], $status['members_seo_name']), "members_status_single" ) . "'>{$status['status_date_formatted_short']}</a>" . (($smallSpace AND $status['_creatorText'] AND $status['status_creator'] AND $status['status_creator'] != 'ipb') ? (" {$this->lang->words['su_via']} {$status['_creatorText']}") : ("")) . "
					</span>
					<span class='mod_links'>
						" . (($status['_canDelete']) ? (" &middot; <a rel=\"nofollow\" href=\"{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=deleteStatus&amp;status_id={$status['status_id']}&amp;k={$this->member->form_hash}\" id=\"statusDelete-{$status['status_id']}\" class=\"__sD __d{$status['status_id']}\">{$this->lang->words['status_delete_link']}</a>") : ("")) . "
						<span id='statusUnlock-{$status['status_id']}' " . (($status['_isLocked'] AND $status['_canUnlock']) ? ("style='display:inline'") : ("style='display:none'")) . "> &middot; <a rel=\"nofollow\"  href=\"{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=unlockStatus&amp;status_id={$status['status_id']}&amp;k={$this->member->form_hash}\" id=\"statusUnlockLink-{$status['status_id']}\" class=\"__sU __u{$status['status_id']}\">{$this->lang->words['status_unlock_link']}</a></span>
						<span id='statusLock-{$status['status_id']}' " . (($status['_canLock'] AND ! $status['_isLocked']) ? ("style='display:inline'") : ("style='display:none'")) . "> &middot; <a rel=\"nofollow\"  href=\"{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=lockStatus&amp;status_id={$status['status_id']}&amp;k={$this->member->form_hash}\" id=\"statusLockLink-{$status['status_id']}\" class=\"__sL __l{$status['status_id']}\">{$this->lang->words['status_lock_link']}</a></span>
						<span id='statusApprove-{$status['status_id']}' " . ((!$status['status_approved'] AND $status['_canApprove']) ? ("style='display:inline'") : ("style='display:none'")) . "> &middot; <a rel=\"nofollow\"  href=\"{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=approveStatus&amp;status_id={$status['status_id']}" . ((! $this->request['status_id'] AND ! $this->request['member_id'] AND ! $this->request['type'] OR $this->request['type'] == 'all') ? ("&amp;rurl=" . base64_encode( $this->registry->output->buildSEOUrl( "app=members&amp;module=profile&amp;section=status&amp;type=all", "public", "", "members_status_all" ) ) . "") : ("")) . "&amp;k={$this->member->form_hash}\">{$this->lang->words['status_approve']}</a></span>
					</span>
				</div>
				<div id=\"statusFeedback-{$status['status_id']}\" class='status_feedback'>
					" . (($status['status_replies'] AND count( $status['replies'] )) ? ("" . (($status['status_replies'] > 3) ? ("
							<div class='status_mini_wrap row2 altrow' id='statusMoreWrap-{$status['status_id']}'>
								<img src=\"{$this->settings['img_url']}/comments.png\" alt=\"\" /> &nbsp;<a href=\"#\" id=\"statusMore-{$status['status_id']}\" class='__showAll __x{$status['status_id']}'>" . sprintf( $this->lang->words['status_show_all_x'], $status['status_replies'] ) . "</a>
							</div>
						") : ("")) . "
						<ul id='statusReplies-{$status['status_id']}' class='ipsList_withtinyphoto clear'>
							" . ( method_exists( $this->registry->getClass('output')->getTemplate('profile'), 'statusReplies' ) ? $this->registry->getClass('output')->getTemplate('profile')->statusReplies($status['replies'], 1) : '' ) . "
						</ul>") : ("")) . "
					<div id='statusReplyBlank-{$status['status_id']}'></div>
					<div id='statusReply-{$status['status_id']}'>
					" . (($status['_userCanReply']) ? ("
						<ul class='ipsList_withtinyphoto reply row2 ipsPad'>
							<li>
								<form id='statusReplyForm-{$status['status_id']}' action='{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=reply&amp;status_id={$status['status_id']}&amp;k={$this->member->form_hash}&amp;id={$this->memberData['member_id']}' method='post'>
									" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array_merge( $this->memberData, array( '_customClass' => 'ipsUserPhoto_tiny', 'alt' => sprintf($this->lang->words['users_photo'],$this->memberData['members_display_name']) ) )) : '' ) . "
									<div class='list_content'>
										<div class=\"status_mini_content\">
											<textarea class='status_textarea input_text' rows='3' cols='50' name='comment-{$status['status_id']}' id='statusText-{$status['status_id']}'></textarea>
											<div class=\"status_submit\"><input type='submit' class='__submit input_submit' id='statusSubmit-{$status['status_id']}' value='{$this->lang->words['status__dfcomment']}' /></div>
										</div>
									</div>
								</form>
								<a href='#' class='__showform' id='statusReplyFormShow-{$status['status_id']}' style='display: none'>{$this->lang->words['status__addcomment']}</a>
							</li>
						</ul>
						<script type='text/javascript'>
							if( $('statusReplyForm-{$status['status_id']}') )
							{
								$('statusReplyForm-{$status['status_id']}').hide();
							}
							
							if( $('statusReplyFormShow-{$status['status_id']}') )
							{
								$('statusReplyFormShow-{$status['status_id']}').show();
							}
						</script>
					") : ("")) . "
					</div>
					<div class='status_mini_wrap row2 altrow' id='statusMaxWrap-{$status['status_id']}' " . (($status['status_replies'] < $this->settings['su_max_replies']) ? ("style='display:none'") : ("")) . ">
						<img src=\"{$this->settings['img_url']}/locked_replies.png\" title=\"{$this->lang->words['status_too_many_replies']}\" alt='x' /> {$this->lang->words['status_too_many_replies']}
					</div>
				</div>
			</div>
		</div>") : ("")) . "

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- statusUpdatesPage --*/
function statusUpdatesPage($updates=array(), $pages='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['statusUpdatesPage'] ) )
{
$count_dc2ef910bc4ab4aef034bf4c1f076144 = is_array($this->functionData['statusUpdatesPage']) ? count($this->functionData['statusUpdatesPage']) : 0;
$this->functionData['statusUpdatesPage'][$count_dc2ef910bc4ab4aef034bf4c1f076144]['updates'] = $updates;
$this->functionData['statusUpdatesPage'][$count_dc2ef910bc4ab4aef034bf4c1f076144]['pages'] = $pages;
}

$_first = reset($updates);

if ( ! isset( $this->registry->templateStriping['recent_status'] ) ) {
$this->registry->templateStriping['recent_status'] = array( FALSE, "row1","row2 altrow");
}
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("status", "0" ) . "<h1 class='ipsType_pagetitle'>{$this->lang->words['status_updates__overview']}</h1>
<br />
<div id='status_standalone_page'>
	" . $this->registry->getClass('output')->getReplacement("header_start") . "<div class='maintitle ipsFilterbar'>
		<ul class='ipsList_inline'>
			<li id='status_all' class='" . ((! $this->request['status_id'] AND ! $this->request['member_id'] AND ! $this->request['type'] OR $this->request['type'] == 'all') ? ("active") : ("")) . "'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=status&amp;type=all", "public",'' ), "true", "members_status_all" ) . "'>{$this->lang->words['status__all_updates']}</a></li>
			" . (($this->memberData['member_id'] AND $this->settings['friends_enabled']) ? ("<li id='status_all' class='tab_toggle " . (($this->request['type'] == 'friends') ? ("active") : ("")) . "'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=status&amp;type=friends", "public",'' ), "true", "members_status_friends" ) . "'>{$this->lang->words['status__myfriends']}</a></li>") : ("")) . "" . (($this->request['member_id']) ? ("
				<li id='status_by_id' class='active'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=status&amp;type=memberall&amp;member_id={$this->request['member_id']}", "public",'' ), array( $this->request['member_id'], $_first['members_seo_name'] ), "members_status_member_all" ) . "'>{$this->lang->words['status__membersupdats']}</a></li>
			") : ("")) . "" . (($this->request['status_id']) ? ("
				<li id='status_by_sid' class='active'><a href='#'>{$this->lang->words['status__singleupdate']}</a></li>
			") : ("")) . "
		</ul>
	</div>" . $this->registry->getClass('output')->getReplacement("header_end") . "
	" . (($this->memberData['member_id'] AND $this->registry->getClass('memberStatus')->canCreate( $this->memberData )) ? ("<div class='status_update row2'>
			<form id='statusForm' action='{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=new&amp;k={$this->member->form_hash}&amp;id={$this->memberData['member_id']}' method='post'>
			<input type='text' id='statusUpdate_page' name='content' style='width:70%' class='input_text'> <input type='submit' class='input_submit' id='statusSubmit_page' value='{$this->lang->words['gbl_post']}' />
			" . (((IPSLib::twitter_enabled() OR IPSLib::fbc_enabled() ) AND ( $this->memberData['fb_uid'] OR $this->memberData['twitter_id'] )) ? ("<p class='desc' style='padding-top:5px;'>{$this->lang->words['st_update']}
					" . ((IPSLib::twitter_enabled() AND ( $this->memberData['twitter_id'] )) ? ("<input type='checkbox' id='su_Twitter' value='1' name='su_Twitter' /> <img src=\"{$this->settings['public_dir']}style_status/twitter.png\" style='vertical-align:top' alt='' />") : ("")) . "
					" . ((IPSLib::fbc_enabled() AND ( $this->memberData['fb_uid'] )) ? ("<input type='checkbox' id='su_Facebook' value='1' name='su_Facebook' /> <img src=\"{$this->settings['public_dir']}style_status/facebook.png\" style='vertical-align:top' alt='' />") : ("")) . "
				</p>") : ("")) . "
			</form>
		</div>") : ("")) . "
	<div id=\"status_wrapper\" class='ipsBox'>
		" . ((count( $updates )) ? ("
			" . ( method_exists( $this->registry->getClass('output')->getTemplate('profile'), 'statusUpdates' ) ? $this->registry->getClass('output')->getTemplate('profile')->statusUpdates($updates) : '' ) . "
		") : ("
			<p class='no-status'>{$this->lang->words['status_updates_none']}</p>
		")) . "
	</div>" . $this->registry->getClass('output')->getReplacement("box_end") . "
" . (($pages) ? ("
	<div class='topic_controls clearfix'>
		{$pages}
	</div>
") : ("")) . "
</div>";
return $IPBHTML;
}

/* -- tabFriends --*/
function tabFriends($friends=array(), $member=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['tabFriends'] ) )
{
$count_5d9d9f4a824382a622c9635fb8d20455 = is_array($this->functionData['tabFriends']) ? count($this->functionData['tabFriends']) : 0;
$this->functionData['tabFriends'][$count_5d9d9f4a824382a622c9635fb8d20455]['friends'] = $friends;
$this->functionData['tabFriends'][$count_5d9d9f4a824382a622c9635fb8d20455]['member'] = $member;
}
$IPBHTML .= "<div class='general_box'>
	" . (($this->settings['friends_enabled'] AND $this->memberData['g_can_add_friends'] AND $member['pp_setting_count_friends']) ? ("<div class='friend_list clear' id='friend_list'>
			<h3>{$this->lang->words['m_title_friends']}</h3>
			" . ((is_array($friends) and count($friends)) ? ("
				<ul class='clearfix'>
				".$this->__f__49c9cb7631a6b228e7d14d7611bd2f86($friends,$member)."				</ul>				
			") : ("
				<p class='ipsPad'>
					<em>{$member['members_display_name']} {$this->lang->words['no_friends_yet']}</em>
				</p>
			")) . "
		</div>
<br />
        {$pagination}") : ("")) . "
</div>";
return $IPBHTML;
}


function __f__49c9cb7631a6b228e7d14d7611bd2f86($friends=array(), $member=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $friends as $friend )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					<li>
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$friend['member_id']}", "public",'' ), "{$friend['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}' class='ipsUserPhotoLink'>
							<img src='{$friend['pp_small_photo']}' alt='{$this->lang->words['photo']}' class='ipsUserPhoto ipsUserPhoto_medium' />
						</a><br />
						<span class='name'>
							" . IPSMember::makeProfileLink($friend['members_display_name_short'], $friend['member_id'], $friend['members_seo_name']) . "
						</span>
					</li>
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- tabNoContent --*/
function tabNoContent($langkey) {
$IPBHTML = "";
$IPBHTML .= "<div class='content_border'><div class='no_messages row1'>{$this->lang->words[ $langkey ]}</div></div>";
return $IPBHTML;
}

/* -- tabPosts --*/
function tabPosts($content) {
$IPBHTML = "";
$IPBHTML .= "<div class='content_border'>
	{$content}
</div>";
return $IPBHTML;
}

/* -- tabReputation --*/
function tabReputation($member, $currentApp='', $type='', $supportedApps=array(), $processedResults='', $pagination='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['tabReputation'] ) )
{
$count_d23371b42318d586244c137f8f8eab9c = is_array($this->functionData['tabReputation']) ? count($this->functionData['tabReputation']) : 0;
$this->functionData['tabReputation'][$count_d23371b42318d586244c137f8f8eab9c]['member'] = $member;
$this->functionData['tabReputation'][$count_d23371b42318d586244c137f8f8eab9c]['currentApp'] = $currentApp;
$this->functionData['tabReputation'][$count_d23371b42318d586244c137f8f8eab9c]['type'] = $type;
$this->functionData['tabReputation'][$count_d23371b42318d586244c137f8f8eab9c]['supportedApps'] = $supportedApps;
$this->functionData['tabReputation'][$count_d23371b42318d586244c137f8f8eab9c]['processedResults'] = $processedResults;
$this->functionData['tabReputation'][$count_d23371b42318d586244c137f8f8eab9c]['pagination'] = $pagination;
}
$IPBHTML .= "<div class='general_box'>
	<div class='maintitle ipsFilterbar clearfix'>
		" . ((count( $supportedApps ) > 1) ? ("
			<ul class='ipsList_inline ipsType_smaller left'>
				".$this->__f__be8f7f67b3e6e8715b144405c7c5e2df($member,$currentApp,$type,$supportedApps,$processedResults,$pagination)."			</ul>
		") : ("")) . "
		<ul class='ipsList_inline ipsType_smaller right'>
			" . (($this->memberData['gbw_view_reps']) ? ("<li " . (($type == 'given') ? ("class='active'") : ("")) . ">
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$member['member_id']}&amp;tab=reputation&amp;app_tab={$currentApp}&amp;type=given", "public",'' ), "{$member['members_seo_name']}", "showuser" ) . "'>
						{$this->lang->words['reputation_given']}
					</a>
				</li>") : ("")) . "
			<li " . (($type == 'received') ? ("class='active'") : ("")) . ">
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$member['member_id']}&amp;tab=reputation&amp;app_tab={$currentApp}&amp;type=received", "public",'' ), "{$member['members_seo_name']}", "showuser" ) . "'>
					{$this->lang->words['reputation_received']}
				</a>
			</li>
		</ul>
	</div>
	" . (($processedResults) ? ("
		{$processedResults}
	") : ("
		<div class='no_messages'>{$this->lang->words['reputation_empty']}</div>
	")) . "
	" . (($pagination) ? ("
		<br />
		{$pagination}
		<br class='clear' />
	") : ("")) . "
</div>";
return $IPBHTML;
}


function __f__be8f7f67b3e6e8715b144405c7c5e2df($member, $currentApp='', $type='', $supportedApps=array(), $processedResults='', $pagination='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $supportedApps as $_app )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					<li " . (($_app['app_directory'] == $currentApp) ? ("class='active'") : ("")) . ">
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$member['member_id']}&amp;tab=reputation&amp;app_tab={$_app['app_directory']}&amp;type={$type}", "public",'' ), "{$member['members_seo_name']}", "showuser" ) . "'>
							" . IPSLib::getAppTitle($_app['app_directory']) . "
						</a>
					</li>
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- tabReputation_calendar --*/
function tabReputation_calendar($results) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['tabReputation_calendar'] ) )
{
$count_8d59ba1c1d99d0c9ab683daf35f9a1fd = is_array($this->functionData['tabReputation_calendar']) ? count($this->functionData['tabReputation_calendar']) : 0;
$this->functionData['tabReputation_calendar'][$count_8d59ba1c1d99d0c9ab683daf35f9a1fd]['results'] = $results;
}
$IPBHTML .= "<div class='ipsBox'>
	".$this->__f__73988f18b550c6802e0157388890f97e($results)."</div>";
return $IPBHTML;
}


function __f__73988f18b550c6802e0157388890f97e($results)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $results as $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		" . (($data['type'] == 'comment_id') ? ("<div class='post_block hentry clear no_sidebar ipsBox_container'>
				<div class='post_wrap'>
					" . (($data['comment_mid']) ? ("
						<h3 class='row2'>
					") : ("
						<h3 class='guest row2'>
					")) . "
						<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=calendar&amp;module=calendar&amp;section=view&amp;do=showevent&amp;event_id={$data['event_id']}", "public",'' ), "{$data['event_title_seo']}", "cal_event" ) . "\">" . IPSText::truncate( $data['event_title'], 80) . "</a>
					</h3>
					<div class='post_body'>
						<p class='posted_info desc lighter ipsType_small'>
							<img src='{$data['pp_thumb_photo']}' class='ipsUserPhoto ipsUserPhoto_tiny' /> {$this->lang->words['posted']} {$this->lang->words['by']}
							" . (($data['member_id']) ? ("<span class=\"author vcard\">" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($data) : '' ) . "</span>") : ("{$data['members_display_name']}")) . "
							{$this->lang->words['on']} <abbr class=\"published\" title=\"" . date( 'c', $data['comment_date'] ) . "\">" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($data['comment_date'],"long", 0)) . "</abbr>
							{$this->lang->words['cal_in']}
							<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=calendar&amp;module=calendar&amp;section=view&amp;do=showevent&amp;event_id={$data['event_id']}", "public",'' ), "{$data['event_title_seo']}", "cal_event" ) . "\">{$data['event_title']}</a>
						</p>
						<div class='post entry-content clearfix'>
							{$data['comment_text']}
							<br />
							" . ( method_exists( $this->registry->getClass('output')->getTemplate('global_other'), 'repButtons' ) ? $this->registry->getClass('output')->getTemplate('global_other')->repButtons($data['author'], array_merge( array( 'primaryId' => $data['comment_id'], 'domLikeStripId' => 'like_comment_id_' . $data['comment_id'], 'domCountId' => 'rep_comment_id_' . $data['comment_id'], 'app' => 'calendar', 'type' => 'comment_id', 'likeFormatted' => $data['repButtons']['formatted'] ), $data )) : '' ) . "
						</div>
					</div>
				</div>
				<br />
			</div>
			<br />") : ("<div class='post_block hentry clear no_sidebar ipsBox_container'>
				<div class='post_wrap'>
					" . (($data['event_member_id']) ? ("
						<h3 class='row2'>
					") : ("
						<h3 class='guest row2'>
					")) . "
						<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=calendar&amp;module=calendar&amp;section=view&amp;do=showevent&amp;event_id={$data['event_id']}", "public",'' ), "{$data['event_title_seo']}", "cal_event" ) . "\">" . IPSText::truncate( $data['event_title'], 80) . "</a>
					</h3>
					<div class='post_body'>
						<p class='posted_info desc lighter ipsType_small'>
							<img src='{$data['pp_thumb_photo']}' class='ipsUserPhoto ipsUserPhoto_tiny' /> {$this->lang->words['posted']} {$this->lang->words['by']}
							" . (($data['member_id']) ? ("<span class=\"author vcard\">" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($data) : '' ) . "</span>") : ("{$data['members_display_name']}")) . "
							{$this->lang->words['on']} <abbr class=\"published\" title=\"" . date( 'c', $data['event_saved'] ) . "\">" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($data['event_saved'],"long", 0)) . "</abbr>
						</p>
						<div class='post entry-content clearfix'>
							{$data['event_content']}
							<br />
							" . ( method_exists( $this->registry->getClass('output')->getTemplate('global_other'), 'repButtons' ) ? $this->registry->getClass('output')->getTemplate('global_other')->repButtons($data, array_merge( array( 'primaryId' => $data['event_id'], 'domLikeStripId' => 'like_event_id_' . $data['event_id'], 'domCountId' => 'rep_event_id_' . $data['event_id'], 'app' => 'calendar', 'type' => 'event_id', 'likeFormatted' => $data['repButtons']['formatted'] ), $data )) : '' ) . "
						</div>
					</div>
				</div>
				<br />
			</div>
			<br />")) . "
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- tabReputation_posts --*/
function tabReputation_posts($results) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['tabReputation_posts'] ) )
{
$count_91b523aec60f1c315f97f4519ff22795 = is_array($this->functionData['tabReputation_posts']) ? count($this->functionData['tabReputation_posts']) : 0;
$this->functionData['tabReputation_posts'][$count_91b523aec60f1c315f97f4519ff22795]['results'] = $results;
}
$IPBHTML .= "<div class='ipsBox'>
	".$this->__f__c48e58e5485b68c48fa7cf22d8db1708($results)."</div>";
return $IPBHTML;
}


function __f__9c98841cdf7b24a2a7776837bdf4aaf6($results,$data='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $data['_forum_trail'] as $i => $f )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
								" . (($i+1 == count( $data['_forum_trail'] )) ? ("<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$f[1]}", "public",'' ), "{$f[2]}", "showforum" ) . "'>{$f[0]}</a>") : ("")) . "
							
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__c48e58e5485b68c48fa7cf22d8db1708($results)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $results as $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<div class='post_block hentry clear no_sidebar ipsBox_container'>
			<div class='post_wrap'>
				<h3 class='" . (($data['member_id']) ? ("guest ") : ("")) . "row2'>
					<span class='post_id right ipsType_small desc blend_links'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$data['topic_id']}&amp;view=findpost&amp;p={$data['pid']}", "public",'' ), "{$data['title_seo']}", "showtopic" ) . "' rel='bookmark' title='{$data['topic_title']}{$this->lang->words['link_to_post']} #{$data['pid']}'>#{$data['pid']}</a></span>
					<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$data['tid']}", "public",'' ), "{$data['title_seo']}", "showtopic" ) . "\">" . IPSText::truncate( $data['topic_title'], 80) . "</a>
				</h3>
				<div class='post_body'>
					<p class='posted_info desc lighter ipsType_small'>
						<img src='{$data['pp_thumb_photo']}' class='ipsUserPhoto ipsUserPhoto_tiny' /> {$this->lang->words['posted_by']} " . (($data['member_id']) ? ("<span class=\"author vcard\">" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($data) : '' ) . "</span>") : ("" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($data) : '' ) . "")) . "
						{$this->lang->words['on']} <abbr class=\"published\" title=\"" . date( 'c', $data['post_date'] ) . "\">" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($data['post_date'],"long", 0)) . "</abbr>
						" . (($data['_forum_trail']) ? ("
							in
							".$this->__f__9c98841cdf7b24a2a7776837bdf4aaf6($results,$data)."						") : ("")) . "
					</p>
					<div class='post entry-content clearfix'>
						{$data['post']}
						<br />
						" . ( method_exists( $this->registry->getClass('output')->getTemplate('global_other'), 'repButtons' ) ? $this->registry->getClass('output')->getTemplate('global_other')->repButtons($data, array_merge( array( 'primaryId' => $data['pid'], 'domLikeStripId' => 'like_post_' . $data['pid'], 'domCountId' => 'rep_post_' . $data['pid'], 'app' => 'forums', 'type' => 'pid', 'likeFormatted' => $data['repButtons']['formatted'], 'has_given_rep' => $data['repButtons']['iLike'] ), $data )) : '' ) . "
					</div>
				</div>
			</div>
			<br />
		</div>
		<br />
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- tabSingleColumn --*/
function tabSingleColumn($row=array(), $read_more_link='', $url='', $title='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['tabSingleColumn'] ) )
{
$count_ec4257e8c097377efd385b1af1b9181c = is_array($this->functionData['tabSingleColumn']) ? count($this->functionData['tabSingleColumn']) : 0;
$this->functionData['tabSingleColumn'][$count_ec4257e8c097377efd385b1af1b9181c]['row'] = $row;
$this->functionData['tabSingleColumn'][$count_ec4257e8c097377efd385b1af1b9181c]['read_more_link'] = $read_more_link;
$this->functionData['tabSingleColumn'][$count_ec4257e8c097377efd385b1af1b9181c]['url'] = $url;
$this->functionData['tabSingleColumn'][$count_ec4257e8c097377efd385b1af1b9181c]['title'] = $title;
}
$IPBHTML .= "<div class='post_block no_sidebar'>
	<div class='post_wrap'>
		" . (($title) ? ("" . (($url) ? ("
				<h3 class='row2'><a href=\"$url\" title=\"{$this->lang->words['view_topic']}\">" . IPSText::truncate( $title, 90 ) . "</a></h3>
			") : ("
				<h3 class='row2'>" . IPSText::truncate( $title, 90 ) . "</h3>
			")) . "") : ("")) . "
		<div class='post_body'>
			<p class='posted_info'>
				" . (($row['_raw_date']) ? ("" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($row['_raw_date'],"long", 0)) . "") : ("{$this->lang->words['posted']} {$row['_date_array']['mday']} {$row['_date_array']['smonth']} {$row['_date_array']['year']}")) . "
			</p>
			<div class='post'>
				{$row['post']}
			</div>
		</div>
	</div>
	<br />
</div>";
return $IPBHTML;
}

/* -- tabStatusUpdates --*/
function tabStatusUpdates($updates=array(), $actions, $member=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['tabStatusUpdates'] ) )
{
$count_c4ab22813b7e28d0471c7f6e12997eb6 = is_array($this->functionData['tabStatusUpdates']) ? count($this->functionData['tabStatusUpdates']) : 0;
$this->functionData['tabStatusUpdates'][$count_c4ab22813b7e28d0471c7f6e12997eb6]['updates'] = $updates;
$this->functionData['tabStatusUpdates'][$count_c4ab22813b7e28d0471c7f6e12997eb6]['actions'] = $actions;
$this->functionData['tabStatusUpdates'][$count_c4ab22813b7e28d0471c7f6e12997eb6]['member'] = $member;
}

if ( ! isset( $this->registry->templateStriping['recent_status'] ) ) {
$this->registry->templateStriping['recent_status'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "<div class='content_border'><h3 class='bar noTopBorder'>{$this->lang->words['pp_tab_statusupdates']}</h3>
" . (($this->memberData['member_id'] AND ( $this->memberData['member_id'] == $member['member_id'] ) AND $this->registry->getClass('memberStatus')->canCreate( $member )) ? ("<div class='status_update'>
		<form id='statusForm' action='{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=new&amp;k={$this->member->form_hash}&amp;id={$this->memberData['member_id']}&amp;forMemberId={$member['member_id']}' method='post'>
		<input type='text' name='content' id='statusUpdate_page' class='input_text' /> <input type='submit' class='input_submit' id='statusSubmit_page' value='{$this->lang->words['gbl_post']}' />
		" . ((( IPSLib::loginMethod_enabled('facebook') AND $this->memberData['fb_uid'] ) OR ( IPSLib::loginMethod_enabled('twitter') AND $this->memberData['twitter_id'] )) ? ("<p class='desc' style='padding-top:5px;'>{$this->lang->words['st_update']}
				" . ((IPSLib::loginMethod_enabled('twitter') AND $this->memberData['twitter_id']) ? ("<input type='checkbox' id='su_Twitter' value='1' name='su_Twitter' /> <img src=\"{$this->settings['public_dir']}style_status/twitter.png\" style='vertical-align:top' alt='' />") : ("")) . "
				" . ((IPSLib::loginMethod_enabled('facebook') AND $this->memberData['fb_uid']) ? ("&nbsp;<input type='checkbox' id='su_Facebook' value='1' name='su_Facebook' /> <img src=\"{$this->settings['public_dir']}style_status/facebook.png\" style='vertical-align:top' alt='' />") : ("")) . "
			</p>") : ("")) . "
		</form>
	</div>") : ("")) . "
" . (($this->memberData['member_id'] && $this->memberData['member_id'] != $member['member_id'] && $member['pp_setting_count_comments'] AND $this->registry->getClass('memberStatus')->canCreate( $this->memberData, $member )) ? ("
	<div class='status_update'>
		<form id='commentForm' action='{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=new&amp;k={$this->member->form_hash}&amp;id={$this->memberData['member_id']}&amp;forMemberId={$member['member_id']}' method='post'>
				<input type='hidden' name='member_id' value='{$member['member_id']}' />
				<input type='hidden' name='auth_key' value='{$this->member->form_hash}' />
				<div id='post_comment'>
					<input type='text' class='input_text' cols='50' rows='3' id='statusUpdate_page' name='content' data-for-member-id=\"{$member['member_id']}\" />
					<input type='submit' class='ipsButton' value='{$this->lang->words['comment_submit_post']}' data-for-member-id=\"{$member['member_id']}\" id='statusSubmit_page' />
				</div> 
		</form>
	</div>
") : ("")) . "
<div class='ipsBox clearfix'>
	<div id=\"status_wrapper\" data-member=\"{$member['member_id']}\">
		" . ((count( $updates )) ? ("
			" . ( method_exists( $this->registry->getClass('output')->getTemplate('profile'), 'statusUpdates' ) ? $this->registry->getClass('output')->getTemplate('profile')->statusUpdates($updates) : '' ) . "
			<div class='short'>
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=status&amp;type=memberall&amp;member_id={$member['member_id']}", "public",'' ), array($member['member_id'], $member['members_seo_name']), "members_status_member_all" ) . "' class='ipsButton_secondary'>{$this->lang->words['status__viewall']}</a>
			</div>
		") : ("
			<p class='ipsBox_container ipsPad' id='noStatusUpdates'>{$this->lang->words['status_updates_none']}</p>
		")) . "
	</div>
</div>
</div>";
return $IPBHTML;
}

/* -- tabTopics --*/
function tabTopics($content) {
$IPBHTML = "";
$IPBHTML .= "<div class='content_border'>
	{$content}
</div>";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>