<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 9               */
/* CACHE FILE: Generated: Thu, 20 Aug 2015 20:18:36 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_boards_9 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['boardIndexTemplate'] = array('showSubForumsLit','subforums','canSeeLastInfoRedirect','hasUnreadClass','hasUnread','hasQueuedAndCanSeeIcon','showSubForums','hideTopicInTitle','hideDateUrl','lastPosterID','hideLastInfo','canSeeLastInfo','forumRedirect','forums','canSeeLastInfoHeader','cat_has_forums','categories','side_blocks','markerhasunread','markernotredirect','markerforums','markerhasforums','markercategories','boardIndexTop','sideBarEnabledL','sidebarclosed','cats_forums','sidebarclosed2','sideBarEnabled2','markercatforums','reputationType','reputationEnabled','statsLinks','showActive','showTotals','showTotals','onlineListEnabled','activeNames');
$this->_funcHooks['hookFacebookActivity'] = array('fbAppIdPresent');
$this->_funcHooks['hookGroupNameIndicator'] = array('showGroupNameIndicator');
$this->_funcHooks['hookRecentTopics'] = array('topics_hook','recenttopics');
$this->_funcHooks['hooksos_topicosrecentes_parseTopic'] = array('notLastFt','topicsForumTrail','haslastpage','pages','hasmodlinks','solvedBadge','hasPrefix','hasTags','multipages','queuedpostsImg','deletedPostsImg','isHot','replylang','isLink');
$this->_funcHooks['hooksos_topicosrecentes_tema1'] = array('topicosrecentes_hook');
$this->_funcHooks['hooksos_topicosrecentesAjax_tema1'] = array('topicosrecentes_hook');
$this->_funcHooks['hookTagCloud'] = array('eachTag');
$this->_funcHooks['statusReplies'] = array('canDelete','isFirstCycle','innerLoop');
$this->_funcHooks['statusUpdates'] = array('canDelete','isLocked','canLock','noLocked','cImg','hasRepliesMain','hasRepliesButCannotReply','canReplyMain','hasMore','hasReplies','canReply','outerLoop');


}

/* -- boardIndexTemplate --*/
function boardIndexTemplate($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['boardIndexTemplate'] ) )
{
$count_f08f9efcde43fe5008587ddd8b74d899 = is_array($this->functionData['boardIndexTemplate']) ? count($this->functionData['boardIndexTemplate']) : 0;
$this->functionData['boardIndexTemplate'][$count_f08f9efcde43fe5008587ddd8b74d899]['lastvisit'] = $lastvisit;
$this->functionData['boardIndexTemplate'][$count_f08f9efcde43fe5008587ddd8b74d899]['stats'] = $stats;
$this->functionData['boardIndexTemplate'][$count_f08f9efcde43fe5008587ddd8b74d899]['cat_data'] = $cat_data;
$this->functionData['boardIndexTemplate'][$count_f08f9efcde43fe5008587ddd8b74d899]['show_side_blocks'] = $show_side_blocks;
$this->functionData['boardIndexTemplate'][$count_f08f9efcde43fe5008587ddd8b74d899]['side_blocks'] = $side_blocks;
}
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("board", "0" ) . "

" . ((true) ? ("") : ("")) . "
<div id='board_index' class='ipsLayout " . (($this->templateVars['sidebar_enabled']) ? ("ipsLayout_withright") : ("")) . " ipsLayout_largeright clearfix " . ((IPSCookie::get('hide_sidebar') == '1') ? ("no_sidebar") : ("")) . "'>	
	<div id='categories' class='ipsLayout_content clearfix'>
	<!-- CATS AND FORUMS -->
		" . ((is_array( $cat_data ) AND count( $cat_data )) ? ("
			".$this->__f__92a0142a0f74372c0ce8722bf5f1b0dd($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks)."		") : ("")) . "
	</div>
	" . (($this->templateVars['sidebar_enabled']) ? ("<div id='index_stats' class='ipsLayout_right clearfix' " . ((IPSCookie::get('hide_sidebar') == '1') ? ("style='display: none'") : ("")) . ">
			".$this->__f__d412a4e2dcc31b2282e6646eabe457c3($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks)."		</div>
		<a href='#' id='toggle_sidebar' title='{$this->lang->words['toggle_sidebar']}' data-closed=\"{$this->lang->words['_laquo']}\" data-open=\"&times;\">&nbsp;</a>") : ("")) . "
</div>
<script type='text/javascript'>
//<![CDATA[
	var markerURL  = ipb.vars['base_url'] + \"app=forums&module=ajax&section=markasread&i=1\"; // Ajax URL so don't use &amp;
	var unreadIcon = \"<img src='{$this->settings['img_url']}/f_icon_read.png' />\";
	
	" . ((is_array( $cat_data ) AND count( $cat_data )) ? ("
		".$this->__f__cc45cc4f799733e1d98600dd04dd6adc($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks)."	") : ("")) . "
//]]>
</script>
<div class=\"category_block block_wrap\">
	<h3 class=\"maintitle\">
		<ul id='stat_links' class='ipsList_inline right ipsType_small'>
			" . ((1==1) ? ("<li>
					<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=extras&amp;section=stats&amp;do=leaders", "public",'' ), "", "" ) . "\" title=\"{$this->lang->words['sm_forum_leaders_title']}\">{$this->lang->words['sm_forum_leaders']}</a>
				</li>
				<li>
					<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=extras&amp;section=stats", "public",'' ), "", "" ) . "\" title=\"{$this->lang->words['sm_all_posters_title']}\">{$this->lang->words['sm_today_posters']}</a>
				</li>
				<li>
					<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=list&amp;max_results=20&amp;sort_key=posts&amp;sort_order=desc&amp;filter=ALL", "public",'' ), "false", "" ) . "\" title=\"{$this->lang->words['sm_overall_posters_title']}\">{$this->lang->words['sm_overall_posters']}</a>
				</li>
				" . (($this->settings['reputation_enabled']) ? ("<li>
						<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=reputation&amp;section=most", "public",'' ), "most_liked", "most_liked" ) . "\">
							" . (($this->settings['reputation_point_types'] == 'like') ? ("
								{$this->lang->words['most_rep_likes']}
							") : ("
								{$this->lang->words['most_rep_rep']}
							")) . "
						</a>
					</li>") : ("")) . "") : ("")) . "
		</ul>

		" . (($this->settings['show_active'] && $this->memberData['gbw_view_online_lists']) ? ("" . sprintf( $this->lang->words['online_right_now'], $stats['TOTAL'] ) . "") : ("")) . " | " . (($this->settings['show_totals']) ? ("{$this->lang->words['total_members']}: <font color='white'>{$stats['info']['mem_count']}</font> | {$this->lang->words['online_at_once']}: <font color='white'>{$stats['info']['most_online']}</font> | {$this->lang->words['total_posts']}: <font color='white'>{$stats['info']['total_posts']}</font>") : ("")) . "
	</h3>
" . (($this->settings['show_totals']) ? ("
<!--
<div class='category_block block_wrap'>
	<h3 class='maintitle'>
			<div id='board_stats'>
				<ul class='ipsType_small ipsList_inline'>
					<li class='clear'>
						<span class='value'>{$stats['info']['total_posts']}</span>
						{$this->lang->words['total_posts']}
					</li>
					<li class='clear'>
						<span class='value'>{$stats['info']['mem_count']}</span>
						{$this->lang->words['total_members']}
					</li>
					<li class='clear'>
						" . IPSMember::makeProfileLink( $stats['info']['last_mem_name'], $stats['info']['last_mem_id'], $stats['info']['last_mem_seo'], 'value' ) . "
						{$this->lang->words['newest_member']}
					</li>
					<li class='clear' data-tooltip='{$stats['info']['most_time']}'>
						<span class='value'>{$stats['info']['most_online']}</span>
						{$this->lang->words['online_at_once']}
					</li>
				</ul>
			</div>
	</h3>
	<div class='border'>
	</div>
	<br />
	<br />
</div>
-->
") : ("")) . "
	<div class=\"border\">
		<div class=\"ipsBox table_wrap removeDefault\">
			<div class=\"ipsBox_container\">
				<table class='ipb_table' summary=\"\">
					<tr class='header hide'>
						<th scope='col' class='col_c_forum'>&nbsp;</th>
					</tr>
					<tr class='notnew'>
						<td scope='col'>
							" . (($this->settings['show_active']) ? ("<p class='statistics_brief desc'>
									" . sprintf( $this->lang->words['active_users_detail'], $stats['MEMBERS'], $stats['GUESTS'], $stats['ANON'] ) . "
									" . (($this->settings['allow_online_list']) ? ("&nbsp;&nbsp;<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=online&amp;sort_order=desc", "public",'' ), "", "" ) . "'>({$this->lang->words['online_link']})</a>") : ("")) . "
								</p>") : ("")) . "
						</td>
					</tr>
					<tr class='notnew'>
						<td scope='col'>
							" . ((count($stats['NAMES']) && $this->settings['show_active']) ? ("
								<br />
								<p>
									<span class='name'>" . implode( ",</span> <span class='name'>", $stats['NAMES'] ) . "</span>
								</p>
							") : ("")) . "<!--hook.if.skin_boards.boardIndexTemplate.activeNames.post.endif-->
						</td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>";
return $IPBHTML;
}


function __f__ee8ddae74a999cc6dc648bf971d2de9c($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array(),$_data='',$forum_id='',$forum_data='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $forum_data['subforums'] as $__id => $__data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
																" . (($__data[3]) ? ("<li class='unread'>") : ("<li>")) . "
																	<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$__data[0]}", "public",'' ), "{$__data[2]}", "showforum" ) . "\" title='" . IPSText::striptags( IPSText::htmlspecialchars($__data[1]) ) . "'>{$__data[1]}</a>
																</li>
															
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__c655fc6c0be8641715f4e36f5ea25990($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array(),$_data='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $_data['forum_data'] as $forum_id => $forum_data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
										" . (($forum_data['redirect_on']) ? ("<tr class='redirect_forum' id='f_{$forum_data['id']}'>
												<td class='col_c_icon'>
													<img src='{$this->settings['img_url']}/f_redirect.png' />
												</td>
												<td " . (($this->memberData['gbw_view_last_info']) ? ("colspan='2'") : ("")) . " class='col_c_forum'>
													<h4><strong><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}", "public",'' ), "{$forum_data['name_seo']}", "showforum" ) . "\" title='" . IPSText::striptags( IPSText::htmlspecialchars( $forum_data['name'] ) ) . "'>{$forum_data['name']}</a></strong></h4>
													" . (($forum_data['description']) ? ("<p class='desc forum_desc'>{$forum_data['description']}</p>") : ("")) . "
												</td>
												<td class='desc'>
													<ul class='last_post ipsType_small'>
                                                        <li class='desc lighter'><em>" . $this->registry->getClass('class_localization')->formatNumber( $forum_data['redirect_hits'] ) . " {$this->lang->words['rd_hits']}</em></li></ul>
												</td>
											</tr>") : ("<tr class='" . (($forum_data['_has_unread']) ? ("unread") : ("notnew")) . "'>
												<td class='col_c_icon'>
													" . (($forum_data['_has_unread']) ? ("
														<a id='forum_img_{$forum_data['id']}' href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=forums&amp;section=markasread&amp;marktype=forum&amp;forumid={$forum_data['id']}&amp;returntoforumid={$this->request['f']}&amp;i=1", "public",'' ), "", "" ) . "\" data-tooltip=\"{$this->lang->words['bi_markread']}\" class='forum_marker'><img src='{$this->settings['img_url']}/f_icon.png' /></a>
													") : ("
														<img src='{$this->settings['img_url']}/f_icon_read.png' />
													")) . "
												</td>
												<td class='col_c_forum'>
													
													<h4>
														" . ((!empty($forum_data['_has_queued_and_can_see_icon'])) ? ("
															<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}&amp;modfilter=unapproved", "public",'' ), "{$forum_data['name_seo']}", "showforum" ) . "' title='{$this->lang->words['view_unapproved']}' class='ipsBadge ipsBadge_orange' data-tooltip=\"" . sprintf( $this->lang->words['f_queued'], $forum_data['queued_topics'], $forum_data['queued_posts']) . "\" style='vertical-align: top'>{$this->lang->words['f_queued_badge']}</a>
														") : ("")) . "
														<strong class='highlight_unread'><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}", "public",'' ), "{$forum_data['name_seo']}", "showforum" ) . "\" title='" . IPSText::striptags( IPSText::htmlspecialchars( $forum_data['name'] ) ) . "'>{$forum_data['name']}</a></strong>
													</h4>

													" . (($forum_data['description']) ? ("<p class='desc __forum_desc forum_desc ipsType_small'>{$forum_data['description']}</p>") : ("")) . "											

													" . (($forum_data['show_subforums'] AND count( $forum_data['subforums'] ) AND $forum_data['show_subforums']) ? ("
														<ol class='ipsList_inline ipsType_small subforums' id='subforums_{$forum_data['id']}'>
															".$this->__f__ee8ddae74a999cc6dc648bf971d2de9c($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks,$_data,$forum_id,$forum_data)."														</ol>
													") : ("")) . "
																					
												</td>
												<td class='col_c_stats ipsType_small'>
													<ul>
														<li>{$forum_data['topics']} {$this->lang->words['topics']}</li>
														<li>{$forum_data['posts']} {$this->lang->words['replies']}</li>
													</ul>
												</td>
" . (($this->memberData['gbw_view_last_info']) ? ("<td class='col_c_post'>
													" . (($forum_data['hide_last_info']) ? ("
														<ul class='last_post ipsType_small'>
															<li class='desc lighter'><em>{$this->lang->words['f_protected']}</em></li>
														</ul>
													") : ("" . (($forum_data['_hide_last_date']) ? ("
														" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array('member_id' => $forum_data['last_poster_id'], 'members_seo_name' => $forum_data['seo_last_name'], 'pp_small_photo' => $forum_data['pp_small_photo'], 'alt' => '' )) : '' ) . "
														") : ("
														" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array('member_id' => $forum_data['last_poster_id'], 'members_seo_name' => $forum_data['seo_last_name'], 'pp_small_photo' => $forum_data['pp_small_photo'], 'alt' => sprintf( $this->lang->words['bindex_userphoto_alt'], $forum_data['last_title'], $forum_data['members_display_name'] ) )) : '' ) . "
														")) . "
														<ul class='last_post ipsType_small'>
															" . ((!$forum_data['last_id']) ? ("
																<li class='desc lighter'><em>{$this->lang->words['f_none']}</em></li>
															") : ("<li>
																	<strong class='highlight_unread'>{$forum_data['last_topic_title']}</strong>
																</li>
                                                                <li>
                                                                    <span class='desc lighter blend_links'>
                                                                    " . (($forum_data['_hide_last_date']) ? ("
                                                                        " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($forum_data['last_post'],"DATE", 0)) . "
                                                                    ") : ("
                                                                        <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$forum_data['last_id']}&amp;view=getlastpost", "public",'' ), "{$forum_data['seo_last_title']}", "showtopic" ) . "' title='{$this->lang->words['view_last_post']}'>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($forum_data['last_post'],"DATE", 0)) . "</a>
                                                                    ")) . "</span>
                                                                    " . (($forum_data['last_poster_id']) ? ("
                                                                        {$this->lang->words['by']} " . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($forum_data) : '' ) . "
                                                                    ") : ("")) . "
                                                                </li>")) . "
															
														</ul>")) . "
												</td>") : ("")) . "
											</tr>")) . "
									
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__92a0142a0f74372c0ce8722bf5f1b0dd($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array())
{
	$_ips___x_retval = '<!--hook.foreach.skin_boards.boardIndexTemplate.categories.outer.pre-->';
	$__iteratorCount = 0;
	foreach( $cat_data as $_data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				" . ((is_array( $_data['forum_data'] ) AND count( $_data['forum_data'] )) ? ("<div id='category_{$_data['cat_data']['id']}' class='category_block block_wrap'>
						" . $this->registry->getClass('output')->getReplacement("header_start") . "<h3 class='maintitle'>
							<a class='toggle right' href='#' title=\"" . sprintf( $this->lang->words['toggle_cat'], IPSText::striptags( IPSText::htmlspecialchars($_data['cat_data']['name'] ) ) ) . "\">" . sprintf( $this->lang->words['toggle_cat'], $_data['cat_data']['name'] ) . "</a> <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$_data['cat_data']['id']}", "public",'' ), "{$_data['cat_data']['name_seo']}", "showforum" ) . "\" title='" . sprintf( $this->lang->words['view_cat'], IPSText::striptags( IPSText::htmlspecialchars($_data['cat_data']['name'] ) ) ) . "'>{$_data['cat_data']['name']}</a>
						</h3>" . $this->registry->getClass('output')->getReplacement("header_end") . "
						<div class='ipsBox table_wrap removeDefault'>
							<div class='ipsBox_container'>
								<table class='ipb_table' summary=\"{$this->lang->words['forums_in_cat']} '{$_data['cat_data']['name']}'\">
									<tr class='header hide'>
										<th scope='col' class='col_c_icon'>&nbsp;</th>
										<th scope='col' class='col_c_forum'>{$this->lang->words['cat_name']}</th>
										<th scope='col' class='col_c_stats stats'>{$this->lang->words['stats']}</th>
										" . (($this->memberData['gbw_view_last_info']) ? ("<th scope='col' class='col_c_post'>{$this->lang->words['last_post_info']}</th>") : ("")) . "
									</tr>
									<!-- / CAT HEADER -->
									".$this->__f__c655fc6c0be8641715f4e36f5ea25990($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks,$_data)."								</table>
							</div>
						</div>" . $this->registry->getClass('output')->getReplacement("box_end") . "
						<br />
					</div>") : ("")) . "
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__d412a4e2dcc31b2282e6646eabe457c3($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array())
{
	$_ips___x_retval = '<!--hook.foreach.skin_boards.boardIndexTemplate.side_blocks.outer.pre-->';
	$__iteratorCount = 0;
	foreach( $side_blocks as $block )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				{$block}
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__d0162dda6a20e0400a2c15ab10fe2f7f($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array(),$_data='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $_data['forum_data'] as $forum_id => $forum_data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					" . ((!$forum_data['redirect_on']) ? ("" . (($forum_data['_has_unread']) ? ("
	ipb.global.registerMarker( \"forum_img_{$forum_data['id']}\", \"{$forum_data['img_new_post']}\", markerURL + \"&forumid={$forum_data['id']}\" );
						") : ("")) . "") : ("")) . "
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__cc45cc4f799733e1d98600dd04dd6adc($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $cat_data as $_data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			" . ((is_array( $_data['forum_data'] ) AND count( $_data['forum_data'] )) ? ("
				".$this->__f__d0162dda6a20e0400a2c15ab10fe2f7f($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks,$_data)."			") : ("")) . "
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- hookBoardIndexStatusUpdates --*/
function hookBoardIndexStatusUpdates($updates=array()) {
$IPBHTML = "";
$IPBHTML .= "<script type='text/javascript' src=\"{$this->settings['public_dir']}js/ips.status.js\"> </script>
<div class='ipsSideBlock clearfix' id='statusHook'>
	<h3>{$this->lang->words['recent_status_updates']}</h3>
	<div class='_sbcollapsable'>
		<div id=\"status_wrapper\">
			<div id=\"status_wrapper_inside\">" . ( method_exists( $this->registry->getClass('output')->getTemplate('boards'), 'statusUpdates' ) ? $this->registry->getClass('output')->getTemplate('boards')->statusUpdates($updates, 1, 1) : '' ) . "</div>
			<div class=\"status_main_content ipsType_small\" style='text-align: center; margin: 10px -10px -10px -10px;'>
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=status&amp;type=all", "public",'' ), "true", "members_status_all" ) . "' style='display: block; padding: 8px; font-weight: bold;'>{$this->lang->words['viewallupdates']}</a>
			</div>
		</div>
	</div>
</div>";
return $IPBHTML;
}

/* -- hookFacebookActivity --*/
function hookFacebookActivity() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hookFacebookActivity'] ) )
{
$count_f9cbb1c3fbc6b3f42fd24f2aad36872d = is_array($this->functionData['hookFacebookActivity']) ? count($this->functionData['hookFacebookActivity']) : 0;
}
$IPBHTML .= "" . ((IPSLib::fbc_enabled()) ? ("
<div class='general_box clearfix'>
	<h3>{$this->lang->words['hook_facebookactivity']}</h3>
	<div  class='block_list clearfix _sbcollapsable'>
		<div><fb:activity site=\"\" width=\"270\" height=\"300\" header=\"false\" border_color=\"#FFF\" colorscheme=\"light\" /></div>
	</div>
</div><div id=\"fb-root\"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({appId: '{$this->settings['fbc_appid']}', status: true, cookie: true,
             xfbml: true});
  };
  (function() {
    var e = document.createElement('script'); e.async = true;
    e.src = document.location.protocol +
      '//connect.facebook.net/{$this->settings['fb_locale']}/all.js';
    document.getElementById('fb-root').appendChild(e);
  }());
</script>
") : ("")) . "";
return $IPBHTML;
}

/* -- hookGroupNameIndicator --*/
function hookGroupNameIndicator($groups=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hookGroupNameIndicator'] ) )
{
$count_552e06a997a984557c26500fcacbdab0 = is_array($this->functionData['hookGroupNameIndicator']) ? count($this->functionData['hookGroupNameIndicator']) : 0;
$this->functionData['hookGroupNameIndicator'][$count_552e06a997a984557c26500fcacbdab0]['groups'] = $groups;
}
$IPBHTML .= "" . ((count( $groups )) ? ("
				<br />
				<ul>
					<li>" . implode( " | ", $groups ) . "</li>
				</ul>
") : ("")) . "";
return $IPBHTML;
}

/* -- hookRecentTopics --*/
function hookRecentTopics($topics) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hookRecentTopics'] ) )
{
$count_3ce6fb2889c716c196d9e9cbc4252d68 = is_array($this->functionData['hookRecentTopics']) ? count($this->functionData['hookRecentTopics']) : 0;
$this->functionData['hookRecentTopics'][$count_3ce6fb2889c716c196d9e9cbc4252d68]['topics'] = $topics;
}
$IPBHTML .= "<!--
" . ((is_array( $topics ) && count( $topics )) ? ("
<div class=\"category_block block_wrap\">
	<h3 class=\"maintitle\">
		<a href=\"javascript:void(0);\" title=\"{$this->lang->words['recently_added_topics']}\">{$this->lang->words['recently_added_topics']}</a>
	</h3>
	<div class=\"border\">
		<div class=\"ipsBox table_wrap removeDefault\">
			<div class=\"ipsBox_container\">
				<table class='ipb_table' summary=\"\">
					<tr class='header hide'>
						<th scope='col' class='col_c_icon'>&nbsp;</th>
						<th scope='col' class='col_c_forum'>&nbsp;</th>
					</tr>
					".$this->__f__0d38ec3cd7840f93bb9456fe1e4264e1($topics)."				</table>
			</div>
		</div>
	</div>
	<br />
</div>
") : ("")) . "
<div class=\"category_block block_wrap\">
	<div class=\"border\">
		<div class=\"ipsBox table_wrap removeDefault\">
			<div class=\"ipsBox_container\">
				<script type=\"text/javascript\" src=\"//vk.com/js/api/openapi.js?115\"></script>
<div id=\"vk_groups\"></div>
<script type=\"text/javascript\">
VK.Widgets.Group(\"vk_groups\", {mode: 0, width: \"270\", height: \"600\", color1: 'FFFFFF', color2: '2B587A', color3: '2c3742'}, 50017713);
</script>
			</div>
		</div>
	</div>
	<br />
</div>
-->";
return $IPBHTML;
}


function __f__0d38ec3cd7840f93bb9456fe1e4264e1($topics)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $topics as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						<tr class='notnew'>
							<td class='col_c_icon'>
								" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto($r) : '' ) . "
							</td>
							<td class='col_c_forum'>
								<h4>
									<strong class='highlight_unread'><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['tid']}", "public",'' ), "{$r['title_seo']}", "showtopic" ) . "\" rel='bookmark' class='ipsType_small' title='" . strip_tags($r['topic_title']) . " {$this->lang->words['topic_started_on']} " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['start_date'],"LONG", 0)) . "'>{$r['topic_title']}</a></strong>
								</h4>
								<p class='desc __forum_desc forum_desc ipsType_small'>" . (($r['members_display_name']) ? ("" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($r) : '' ) . "") : ("{$this->settings['guest_name_pre']}{$r['starter_name']}{$this->settings['guest_name_suf']}")) . " - " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['start_date'],"short", 0)) . "</p>
							</td>
</tr>
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- hooksos_topicosrecentes_parseTopic --*/
function hooksos_topicosrecentes_parseTopic($r=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hooksos_topicosrecentes_parseTopic'] ) )
{
$count_b004fa48ba796e828f68e8764d3aa4a5 = is_array($this->functionData['hooksos_topicosrecentes_parseTopic']) ? count($this->functionData['hooksos_topicosrecentes_parseTopic']) : 0;
$this->functionData['hooksos_topicosrecentes_parseTopic'][$count_b004fa48ba796e828f68e8764d3aa4a5]['r'] = $r;
}

$author = IPSMember::makeProfileLink(IPSMember::makeNameFormatted( $r['topic_data']['nome1'], $r['topic_data']['grupo1']), $r['topic_data']['starter_id']);

$lastposter = IPSMember::makeProfileLink(IPSMember::makeNameFormatted( $r['topic_data']['members_display_name'], $r['topic_data']['member_group_id']), $r['topic_data']['last_poster_id']);
$IPBHTML .= "<li>
	<table class=\"ipb_table topic_list hover_rows\">
		<tr class='__topic " . ((!$r['topic_data']['folder_img']['is_read']) ? ("unread") : ("")) . " expandable' id='trow_{$r['topic_data']['tid']}' data-tid=\"{$r['topic_data']['tid']}\" data-timestamp=\"{$r['topic_data']['last_post']}\">
			<td class='col_f_icon altrow short'>
				" . ( method_exists( $this->registry->getClass('output')->getTemplate('global_other'), 'generateTopicIcon' ) ? $this->registry->getClass('output')->getTemplate('global_other')->generateTopicIcon($r['topic_data']['folder_img'], isset($r['topic_data']['_unreadUrl']) ? $r['topic_data']['_unreadUrl'] : '') : '' ) . "
			</td>
			
			<td class='col_f_content " . (($this->memberData['is_mod'] == 1 || $r['forum_data']['permissions']['TopicSoftDelete']) ? (" with_mod_links") : ("")) . "'>
			   " . (($r['topic_data']['_answeredPid'] !== false) ? ("
					<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=forums&amp;section=findpost&amp;pid={$r['topic_data']['_answeredPid']}", "public",'' ), "", "" ) . "\"><span class='ipsBadge has_icon ipsBadge_green'><img class='icon' src=\"{$this->settings['img_url']}/icon_check_white_8px.png\"> {$this->lang->words['topic_solved']}</span></a>
				") : ("")) . "
				" . ((!empty($r['topic_data']['tags']['formatted']['prefix'])) ? ("
					{$r['topic_data']['tags']['formatted']['prefix']}
				") : ("")) . "
				<h4>{$r['topic_data']['prefix']} " . (($r['topic_data']['topic_hasattach']) ? ("<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=forums&amp;section=attach&amp;tid={$r['topic_data']['tid']}", "public",'' ), "", "" ) . "\" title=\"" . intval($r['topic_data']['topic_hasattach']) . " {$this->lang->words['topic_attach']}\" onclick=\"return ipb.forums.retrieveAttachments( {$r['topic_data']['tid']} );\">" . $this->registry->getClass('output')->getReplacement("post_attach_link") . "</a> ") : ("")) . "<a{$r['topic_data']['style']} id=\"tid-link-{$r['topic_data']['tid']}\" href=\"{$r['topic_data']['_url']}\" title='{$this->lang->words['topic_started_on']} " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['topic_data']['start_date'],"LONG", 0)) . "' class='topic_title'>{$r['topic_data']['title']}</a></h4>
				<br />
				<span class='desc lighter blend_links'>
										" . sprintf( $this->lang->words['topic_started_by'], $author ) . " " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['topic_data']['start_date'],"DATE", 0)) . "
					{$this->lang->words['in_last_topic']}
					".$this->__f__6c3eef20af3a929acc5d7f67f1a3bf91($r)."					" . ((isset($r['topic_data']['tags']) AND $r['topic_data']['tags']) ? ("
						&nbsp; <img src='{$this->settings['img_url']}/icon_tag.png' /> {$r['topic_data']['tags']['formatted']['truncatedWithLinks']}
					") : ("")) . "
				</span>
				" . ((isset( $r['topic_data']['pages'] ) AND is_array( $r['topic_data']['pages'] ) AND count( $r['topic_data']['pages'] )) ? ("
					<ul class='mini_pagination'>
					".$this->__f__42eab4d7b34bb23ad3f5ad0698db1e98($r)."					</ul>
				") : ("")) . "
			</td>
			<td class='col_f_preview __topic_preview'>
				" . (($this->registry->permissions->check( 'read', $r['forum_data'] )) ? ("
					<a href='{$r['topic_data']['_url']}' class='expander closed' title='{$this->lang->words['view_topic_preview']}'>&nbsp;</a>
				") : ("")) . "
			</td>
			<td class='col_f_views desc blend_links'>
				<ul>
					<li>
						" . ((($this->memberData['is_mod'] AND $r['topic_data']['_hasqueued'])) ? ("
							<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['topic_data']['tid']}&amp;modfilter=invisible_posts", "public",'' ), "{$r['topic_data']['title_seo']}", "showtopic" ) . "' title='{$this->lang->words['view_uapproved_posts']}' data-tooltip=\"" . sprintf( $this->lang->words['topic_queued_count'], $r['topic_data']['topic_queuedposts'] ) . "\"><img src='{$this->settings['img_url']}/bullet_error.png' alt='' /></a>
						") : ("")) . "
						" . ((($r['forum_data']['permissions']['PostSoftDeleteSee'] AND $r['topic_data']['topic_deleted_posts'])) ? ("
							<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['topic_data']['tid']}&amp;modfilter=deleted_posts", "public",'' ), "{$r['topic_data']['title_seo']}", "showtopic" ) . "' title='{$this->lang->words['view_deleted_posts']}'><img src='{$this->settings['img_url']}/bullet_delete.png' alt='' /></a>
						") : ("")) . "
						" . (($r['topic_data']['state'] != 'link') ? ("" . (($r['topic_data']['folder_img']['is_hot']) ? ("
								<span class='ipsBadge ipsBadge_orange'>{$this->lang->words['topic_is_hot']}</span>&nbsp;
							") : ("")) . "
							<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=extras&amp;section=stats&amp;do=who&amp;t={$r['topic_data']['tid']}", "public",'' ), "", "" ) . "\" onclick=\"return ipb.forums.retrieveWhoPosted( {$r['topic_data']['tid']} );\">" . $this->registry->getClass('class_localization')->formatNumber( $r['topic_data']['posts'] ) . " " . ((intval($r['topic_data']['posts']) == 1) ? ("{$this->lang->words['reply']}") : ("{$this->lang->words['replies']}")) . "</a>") : ("")) . "
					</li>
					<li class='views desc'>" . $this->registry->getClass('class_localization')->formatNumber( $r['topic_data']['views'] ) . " {$this->lang->words['views']}</li>
				</ul>
			</td>
			<td class='col_f_post'>
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['topic_data']['last_poster_id']}", "public",'' ), "{$r['topic_data']['seo_last_name']}", "showuser" ) . "' class='ipsUserPhotoLink left'>
					<img src='{$r['topic_data']['pp_small_photo']}' class='ipsUserPhoto ipsUserPhoto_mini' />
				</a>
				<ul class='last_post ipsType_small'>
									<li>{$lastposter}</li>
					<li>
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['topic_data']['tid']}&amp;view=getlastpost", "public",'' ), "{$r['topic_data']['title_seo']}", "showtopic" ) . "' title='{$this->lang->words['goto_last_post']}'>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['topic_data']['last_post'],"DATE", 0)) . "</a>
					</li>								
				</ul>
			</td>
		</tr>
	</table>
</li>";
return $IPBHTML;
}


function __f__6c3eef20af3a929acc5d7f67f1a3bf91($r=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $r['topic_data']['forumBreadcrumb'] as $i => $f )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$f[1]}", "public",'' ), "{$f[2]}", "showforum" ) . "'>{$f[0]}</a>&nbsp;" . (($i+1 != count( $r['topic_data']['forumBreadcrumb'] )) ? ("" . $this->registry->getClass('output')->getReplacement("f_nav_sep") . "") : ("")) . "
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__42eab4d7b34bb23ad3f5ad0698db1e98($r=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $r['topic_data']['pages'] as $page )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
							" . (($page['last']) ? ("
								<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['topic_data']['tid']}&amp;st={$page['st']}", "public",'' ), "{$r['topic_data']['title_seo']}", "showtopic" ) . "\" title='{$this->lang->words['topic_goto_page']} {$page['page']}'>{$page['page']} {$this->lang->words['_rarr']}</a></li>
							") : ("
								<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['topic_data']['tid']}&amp;st={$page['st']}", "public",'' ), "{$r['topic_data']['title_seo']}", "showtopic" ) . "\" title='{$this->lang->words['topic_goto_page']} {$page['page']}'>{$page['page']}</a></li>
							")) . "
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- hooksos_topicosrecentes_tema1 --*/
function hooksos_topicosrecentes_tema1($topics=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hooksos_topicosrecentes_tema1'] ) )
{
$count_bbbbdb138af47aafdd4ff98096b1af91 = is_array($this->functionData['hooksos_topicosrecentes_tema1']) ? count($this->functionData['hooksos_topicosrecentes_tema1']) : 0;
$this->functionData['hooksos_topicosrecentes_tema1'][$count_bbbbdb138af47aafdd4ff98096b1af91]['topics'] = $topics;
}

if ( $this->memberData['member_id'] AND $this->memberData['topicosrecentes_showdqtd'] )
		{
			$nr = $this->memberData['recenttopics_qtd'];
		}
		else
		{
			$nr = $this->settings['topicosrecentes_nr'];
		}
$IPBHTML .= "<script src=\"{$this->settings['public_dir']}js/ips.recentTopicsHook.js\" type=\"text/javascript\"></script>
<script src=\"{$this->settings['public_dir']}js/ips.forums.js\" type=\"text/javascript\"></script>
	  <script type=\"text/javascript\">
	ipb.recentTopics.updateInterval = parseInt( {$this->settings['topicosrecentes_updateInterval']} );
		ipb.recentTopics.maxElements	= parseInt( {$nr} );
	ipb.recentTopics.img_disable    = parseInt({$this->settings['topicosrecentes_img_disable']});
</script>

<div id='recentTopicsWrapper' class='category_block block_wrap'>
	<h3 class='maintitle'>
	<span class=\"right\"><ul class=\"ipsFilterbar ipsList_inline ipsType_small\">
	                <a class='toggle right' href='#' title=\"{$this->lang->words['toggle_cat']}\">
	        {$this->lang->words['toggle_cat']}</a></ul>
	                        </span>
	{$this->settings['topicosrecentes_title']}</h3>
	
		<div class='ipsBox_container'>
			<table class='ipb_table topic_list hover_rows'>
				<tr class='header hide'>
					<th scope='col' class='col_f_icon'>&nbsp;</th>
					<th scope='col' class='col_f_topic'>{$this->lang->words['forum_topic']}</th>
					<th scope='col' class='col_f_starter short'>{$this->lang->words['forum_started_by']}</th>
					<th scope='col' class='col_f_views stats'>{$this->lang->words['forum_stats']}</th>
					<th scope='col' class='col_f_post'>{$this->lang->words['forum_last_post_info']}</th>
				</tr>
			</table>
			<!-- BEGIN TOPICS -->
			<ul id='recentTopics_table'>
				".$this->__f__a2d0dd1ba547b7ecf89e0036966e1952($topics)."			</ul>
		</div>
	
</div>
<br />";
return $IPBHTML;
}


function __f__a2d0dd1ba547b7ecf89e0036966e1952($topics=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $topics as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					" . ( method_exists( $this->registry->getClass('output')->getTemplate('boards'), 'hooksos_topicosrecentes_parseTopic' ) ? $this->registry->getClass('output')->getTemplate('boards')->hooksos_topicosrecentes_parseTopic($r) : '' ) . "
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- hooksos_topicosrecentesAjax_tema1 --*/
function hooksos_topicosrecentesAjax_tema1($topics=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hooksos_topicosrecentesAjax_tema1'] ) )
{
$count_7cd0153205a8fa6a38b54c030e477df8 = is_array($this->functionData['hooksos_topicosrecentesAjax_tema1']) ? count($this->functionData['hooksos_topicosrecentesAjax_tema1']) : 0;
$this->functionData['hooksos_topicosrecentesAjax_tema1'][$count_7cd0153205a8fa6a38b54c030e477df8]['topics'] = $topics;
}
$IPBHTML .= "".$this->__f__36eddc7deb7467abe3e81eb2364c7a98($topics)."";
return $IPBHTML;
}


function __f__36eddc7deb7467abe3e81eb2364c7a98($topics=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $topics as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	" . ( method_exists( $this->registry->getClass('output')->getTemplate('boards'), 'hooksos_topicosrecentes_parseTopic' ) ? $this->registry->getClass('output')->getTemplate('boards')->hooksos_topicosrecentes_parseTopic($r) : '' ) . "

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- hookTagCloud --*/
function hookTagCloud($tags) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hookTagCloud'] ) )
{
$count_5b4a508b9e4f331fe51b0498205a16b5 = is_array($this->functionData['hookTagCloud']) ? count($this->functionData['hookTagCloud']) : 0;
$this->functionData['hookTagCloud'][$count_5b4a508b9e4f331fe51b0498205a16b5]['tags'] = $tags;
}
$IPBHTML .= "<div class='ipsSideBlock clearfix'>
	<h3>{$this->lang->words['popular_tags']}</h3>
	<div class='_sbcollapsable'>
		<ul class='ipsList_inline'>
		".$this->__f__1991eab660a51a33ce54b6aed011d5a5($tags)."		</ul>
	</div>
</div>";
return $IPBHTML;
}


function __f__1991eab660a51a33ce54b6aed011d5a5($tags)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $tags['tags'] as $id => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<li><span class=\"{$data['className']}\">{$data['tagWithUrl']}</span></li>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- statusReplies --*/
function statusReplies($replies=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['statusReplies'] ) )
{
$count_abc0f8c12f7960332399825cf0ce4d9e = is_array($this->functionData['statusReplies']) ? count($this->functionData['statusReplies']) : 0;
$this->functionData['statusReplies'][$count_abc0f8c12f7960332399825cf0ce4d9e]['replies'] = $replies;
}
$IPBHTML .= "".$this->__f__ea0bdf4a22d94100ddc3ec70b6838c37($replies)."";
return $IPBHTML;
}


function __f__ea0bdf4a22d94100ddc3ec70b6838c37($replies=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $replies as $reply )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	<div id='statusReply-{$reply['reply_id']}' class='ipsPad_half'>
		" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array_merge( $reply, array( '_customClass' => 'ipsUserPhoto_tiny', 'alt' => sprintf($this->lang->words['users_photo'],$reply['members_display_name']) ) )) : '' ) . "
		<div class='list_content'>
			<div class='right lighter'>
				<span class='desc ipsType_smaller'>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($reply['reply_date'],"manual{%d %b}", 0)) . "&nbsp;&nbsp;</span>
				<span class='desc mod_links ipsType_smaller'>
					" . (($reply['_canDelete']) ? ("<a href=\"{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=deleteReply&amp;status_id={$reply['reply_status_id']}&amp;reply_id={$reply['reply_id']}&amp;k={$this->member->form_hash}\" id=\"statusReplyDelete-{$reply['reply_status_id']}-{$reply['reply_id']}\" class=\"__sDR __dr{$reply['reply_status_id']}-{$reply['reply_id']}\">{$this->lang->words['status_delete_link']}</a>") : ("")) . "
				</span>
			</div>
			<strong>" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($reply) : '' ) . "</strong>
			<p class='index_status_update ipsType_small'>{$reply['reply_content']}</p>
		</div>
	</div>
	" . (($__iteratorCount == count($replies)) ? ("
		<div id='statusReplyBlank-{$reply['reply_status_id']}' style='display: none'></div>
	") : ("")) . "

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- statusUpdates --*/
function statusUpdates($updates=array(), $smallSpace=0, $latestOnly=0) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['statusUpdates'] ) )
{
$count_9d052bc35d88d40aa8425d6acb806888 = is_array($this->functionData['statusUpdates']) ? count($this->functionData['statusUpdates']) : 0;
$this->functionData['statusUpdates'][$count_9d052bc35d88d40aa8425d6acb806888]['updates'] = $updates;
$this->functionData['statusUpdates'][$count_9d052bc35d88d40aa8425d6acb806888]['smallSpace'] = $smallSpace;
$this->functionData['statusUpdates'][$count_9d052bc35d88d40aa8425d6acb806888]['latestOnly'] = $latestOnly;
}
$IPBHTML .= "<script type=\"text/javascript\">
	ipb.status.maxReplies = " . intval($this->settings['su_max_replies']) . ";
	ipb.status.smallSpace = " . intval($smallSpace) . ";
	ipb.status.skin_group = 'boards';
</script>".$this->__f__1d3076f490ed82e42d2409386f373b47($updates,$smallSpace,$latestOnly)."";
return $IPBHTML;
}


function __f__1d3076f490ed82e42d2409386f373b47($updates=array(), $smallSpace=0, $latestOnly=0)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $updates as $id => $status )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	" . (($this->memberData['member_id'] AND $latestOnly AND $status['member_id'] == $this->memberData['member_id']) ? ("
		<script type=\"text/javascript\">
			ipb.status.myLatest = {$status['status_id']};
		</script>
	") : ("")) . "
	<ul class='ipsList_withminiphoto status_list' id='statusWrap-{$status['status_id']}'>
		<li class='clearfix'>
			" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto($status) : '' ) . "
			<div class='list_content'>
				<div id=\"statusContent-{$status['status_id']}\">
					<div class='right desc lighter'>
						<span class='desc mod_links ipsType_smaller'>
							" . (($status['_canDelete']) ? ("<a rel=\"nofollow\" href=\"{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=deleteStatus&amp;status_id={$status['status_id']}&amp;k={$this->member->form_hash}\" id=\"statusDelete-{$status['status_id']}\" class=\"__sD __d{$status['status_id']}\">{$this->lang->words['status_delete_link']}</a>") : ("")) . "
							<span id='statusUnlock-{$status['status_id']}' " . (($status['_isLocked'] AND $status['_canUnlock']) ? ("style='display:inline'") : ("style='display:none'")) . "> &middot; <a rel=\"nofollow\"  href=\"{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=unlockStatus&amp;status_id={$status['status_id']}&amp;k={$this->member->form_hash}\" id=\"statusUnlockLink-{$status['status_id']}\" class=\"__sU __u{$status['status_id']}\">{$this->lang->words['status_unlock_link']}</a></span>
							<span id='statusLock-{$status['status_id']}' " . (($status['_canLock'] AND ! $status['_isLocked']) ? ("style='display:inline'") : ("style='display:none'")) . "> &middot; <a rel=\"nofollow\"  href=\"{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=lockStatus&amp;status_id={$status['status_id']}&amp;k={$this->member->form_hash}\" id=\"statusLockLink-{$status['status_id']}\" class=\"__sL __l{$status['status_id']}\">{$this->lang->words['status_lock_link']}</a></span>
						</span>
						&nbsp;&nbsp;<span class='ipsType_smaller blend_links'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=status&amp;type=single&amp;status_id={$status['status_id']}", "public",'' ), array($status['member_id'], $status['members_seo_name']), "members_status_single" ) . "'>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($status['status_date'],"manual{%d %b}", 0)) . "</a></span>
					</div>
					" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($status) : '' ) . "
					<p class='index_status_update ipsType_small'>{$status['status_content']}</p>
					<span class='desc' id='statusToggle-{$status['status_id']}'>
						<img src=\"{$this->settings['img_url']}/icon_lock.png\" id='statusLockImg-{$status['status_id']}' alt=\"{$this->lang->words['status__locked']}\" " . ((!$status['status_is_locked']) ? ("style='display: none'") : ("")) . " />
						" . ((! $smallSpace AND $status['_creatorImg']) ? ("<img src=\"{$status['_creatorImg']}\" alt='' data-tooltip=\"{$this->lang->words['su_via']} {$status['_creatorText']}\" />") : ("")) . "
						" . (($status['_userCanReply']) ? ("" . (($status['status_replies']) ? ("
								<a href=\"#\" class=\"__sT __t{$status['status_id']} ipsType_smaller \">" . sprintf( $this->lang->words['view_comments_and_add'], $status['status_replies']) . "</a>
							") : ("
								<a href=\"#\" class=\"__sT __t{$status['status_id']} ipsType_smaller\">{$this->lang->words['add_comments_only']}</a>
							")) . "") : ("" . (($status['status_replies']) ? ("
								<a href=\"#\" class=\"__sT __t{$status['status_id']} ipsType_smaller\">" . sprintf( $this->lang->words['view_comments_only'], $status['status_replies']) . "</a>
							") : ("")) . "")) . "
					</span>
					<span class='desc' id='statusToggleOff-{$status['status_id']}' style='display:none'>
						<a href=\"#\" class=\"__sTO __to{$status['status_id']}\">{$this->lang->words['view_comments_collapse']}</a>
					</span>
				</div>
			</div>
			<div id=\"statusFeedback-{$status['status_id']}\" class='status_feedback' style='display:none'>
				<div class='ipsList_withtinyphoto status_list' id='statusReplies-{$status['status_id']}'>
					" . (($status['status_replies'] AND count( $status['replies'] )) ? ("" . (($status['status_replies'] > 3) ? ("
							<div class='status_mini_wrap row2 altrow' id='statusMoreWrap-{$status['status_id']}'>
								<img src=\"{$this->settings['img_url']}/comments.png\" alt=\"\" /> &nbsp;<a href=\"#\" id=\"statusMore-{$status['status_id']}\" class='__showAll __x{$status['status_id']}'>" . sprintf( $this->lang->words['status_show_all_x'], $status['status_replies'] ) . "</a>
							</div>
						") : ("")) . "
						" . ( method_exists( $this->registry->getClass('output')->getTemplate('boards'), 'statusReplies' ) ? $this->registry->getClass('output')->getTemplate('boards')->statusReplies($status['replies']) : '' ) . "") : ("
						<div id='statusReplyBlank-{$status['status_id']}' style='display: none'></div>
					")) . "
				</div>
				" . (($status['_userCanReply']) ? ("
					<div class='ipsList_withtinyphoto status_list status_reply clearfix ipsPad_half' id='statusReply-{$status['status_id']}'>
						" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array_merge( $this->memberData, array( '_customClass' => 'ipsUserPhoto_tiny', 'alt' => sprintf($this->lang->words['users_photo'],$this->memberData['members_display_name']) ) )) : '' ) . "
						<div class='list_content'>
							<form id='statusReplyForm-{$status['status_id']}' action='{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=reply&amp;status_id={$status['status_id']}&amp;k={$this->member->form_hash}&amp;id={$this->memberData['member_id']}' method='post'>
								<textarea class='status_textarea' rows='3' cols='50' name='comment-{$status['status_id']}' id='statusText-{$status['status_id']}'></textarea>
								<div class=\"status_submit\"><input type='submit' class='__submit input_submit' id='statusSubmit-{$status['status_id']}' value='{$this->lang->words['status__dfcomment']}' /></div>
							</form>
							<a href='#' class='__showform' id='statusReplyFormShow-{$status['status_id']}' style='display: none'>{$this->lang->words['status__addcomment']}</a>
						</div>
					</div>
					<script type='text/javascript'>
						if( $('statusReplyForm-{$status['status_id']}') ){
							$('statusReplyForm-{$status['status_id']}').hide();
						}
						if( $('statusReplyFormShow-{$status['status_id']}') ){
							$('statusReplyFormShow-{$status['status_id']}').show();
						}
					</script>
				") : ("")) . "
			</div>
		</li>
	</ul>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- top_reputation_link --*/
function top_reputation_link($link) {
$IPBHTML = "";
$IPBHTML .= "{$link}";
return $IPBHTML;
}

/* -- VNStickyGlobalMessage --*/
function VNStickyGlobalMessage($data) {
$IPBHTML = "";
$IPBHTML .= "<div align='center'>
<style type='text/css'>
#stickymsg{
position: fixed;
{$this->settings['vn_sticky_message_system_location']}: 10px;
line-height: 16px;
{$this->settings['vn_sticky_message_system_position']}: 10px;
z-index: 30000;
opacity: 0.8;
width: 260px;
height: auto;
background: #cf3737;
color: #fff;
text-shadow: rgba(0,0,0,0.3) 0px -1px 0px;
padding: 10px;
text-decoration: none;
font-size: 11px;
font-family: Tahoma;
border: 1px solid #771b1b;
box-shadow: rgba(0,0,0,0.3) 0px 1px 4px, inset #f66c6c 0px 1px 0px;
border-radius: 3px;
}
#stickymsg a{ color: #fff; font-weight:bold; text-decoration: none; }
#stickymsg:hover{ opacity: 1; }
</style><div id='stickymsg'>{$data['message']}</div></div>";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>