<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Sat, 25 Jul 2015 17:29:18 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_search_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['asForumTopics'] = array('notLastFtAsForum','topicsForumTrail','resultIsPostAsForum','isNewPostAsForum');
$this->_funcHooks['searchResults'] = array('subResult','results');


}

/* -- asForumPosts --*/
function asForumPosts($data) {
$IPBHTML = "";
$IPBHTML .= "<template>searchResultsAsPost</template>
<searchResults>
</searchResults>";
return $IPBHTML;
}

/* -- asForumTopics --*/
function asForumTopics($data) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['asForumTopics'] ) )
{
$count_73a3c3ad5c9e68683150d8d902a85d65 = is_array($this->functionData['asForumTopics']) ? count($this->functionData['asForumTopics']) : 0;
$this->functionData['asForumTopics'][$count_73a3c3ad5c9e68683150d8d902a85d65]['data'] = $data;
}
$IPBHTML .= "<searchResult>
	<tid>{$data['tid']}</tid>
	<title>{$data['_shortTitle']}</title>
	<state>{$data['state']}</state>
	<url>" . (($data['_unreadUrl']) ? ("{$data['_unreadUrl']}") : ("" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$data['type_id_2']}&amp;view=" . (($this->request['do']=='new_posts' OR $this->request['do']=='active') ? ("getnewpost") : ("" . (($data['misc']) ? ("findpost&amp;p={$data['misc']}") : ("")) . "")) . "&amp;hl={$this->request['search_higlight']}&amp;fromsearch=1", "public",'' ), "{$data['title_seo']}", "showtopic" ) . "")) . "</url>
	<isRead>" . (($data['_isRead'] == 1) ? ("1") : ("0")) . "</isRead>
	<authorid>{$data['author_id']}</authorid>
	<author>{$data['author_name']}</author>
	".$this->__f__96a98a474dd47b738ccf7b35350d2e0c($data)."</searchResult>";
return $IPBHTML;
}


function __f__96a98a474dd47b738ccf7b35350d2e0c($data)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $data['_forum_trail'] as $i => $f )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "" . (($i+1 == count( $data['_forum_trail'] )) ? ("<forum>{$f[0]}</forum>") : ("")) . "
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- followData --*/
function followData($followData) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- followedContentForumsWrapper --*/
function followedContentForumsWrapper($results) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- followedContentForumsWrapperForums --*/
function followedContentForumsWrapperForums($results) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- followedContentView --*/
function followedContentView($results, $pagination, $total, $error, $contentTypes) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- forumAdvancedSearchFilters --*/
function forumAdvancedSearchFilters($forums, $archivedPostCount=0) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- forumsVncFilters --*/
function forumsVncFilters($data, $currentPrefs) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- helpSearchResult --*/
function helpSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- memberCommentsSearchResult --*/
function memberCommentsSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- memberSearchResult --*/
function memberSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- newContentView --*/
function newContentView($results, $pagination, $total, $sortDropDown, $sortIn, $dateCutSet=0) {
$IPBHTML = "";
$IPBHTML .= "{$results}";
return $IPBHTML;
}

/* -- searchAdvancedForm --*/
function searchAdvancedForm($filters='', $msg='', $current_app, $removed_search_terms=array(), $isFT=false, $canTag=array()) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- searchResults --*/
function searchResults($results, $titlesOnly) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['searchResults'] ) )
{
$count_da7c478e558806a27ef8f2ab6ce4ec22 = is_array($this->functionData['searchResults']) ? count($this->functionData['searchResults']) : 0;
$this->functionData['searchResults'][$count_da7c478e558806a27ef8f2ab6ce4ec22]['results'] = $results;
$this->functionData['searchResults'][$count_da7c478e558806a27ef8f2ab6ce4ec22]['titlesOnly'] = $titlesOnly;
}
$IPBHTML .= "" . ((is_array( $results )) ? ("".$this->__f__b598ad6f09a7a88c2719b851ab67c05f($results,$titlesOnly)."		") : ("")) . "";
return $IPBHTML;
}


function __f__b598ad6f09a7a88c2719b851ab67c05f($results, $titlesOnly)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $results as $result )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			" . (($result['sub']) ? ("
					{$result['html']}
				
			") : ("
					{$result['html']}
				
			")) . "
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- searchResultsAsForum --*/
function searchResultsAsForum($results, $titlesOnly) {
$IPBHTML = "";
$IPBHTML .= "<template>searchResultsAsTopic</template>
<searchResults>
" . ( method_exists( $this->registry->getClass('output')->getTemplate('search'), 'searchResults' ) ? $this->registry->getClass('output')->getTemplate('search')->searchResults($results, $titlesOnly) : '' ) . "
</searchResults>";
return $IPBHTML;
}

/* -- searchResultsWrapper --*/
function searchResultsWrapper($results, $sortDropDown, $sortIn, $pagination, $total, $showing, $search_term, $url_string, $current_key, $removed_search_terms=array(), $limited=0, $wasLimited=false, $search_tags) {
$IPBHTML = "";
$IPBHTML .= "{$results}";
return $IPBHTML;
}

/* -- searchRowGenericFormat --*/
function searchRowGenericFormat($r, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- topicPostSearchResultAsForum --*/
function topicPostSearchResultAsForum($data, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "" . ( method_exists( $this->registry->getClass('output')->getTemplate('search'), 'asForumTopics' ) ? $this->registry->getClass('output')->getTemplate('search')->asForumTopics($data) : '' ) . "";
return $IPBHTML;
}

/* -- userPostsView --*/
function userPostsView($results, $pagination, $total, $member, $limited=0, $wasLimited=false, $beginTime=0, $sortIn=null, $sortDropDown=array()) {
$IPBHTML = "";
$IPBHTML .= "test
<pagination>{$pagination}</pagination>
{$results}";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>